#! /bin/sh
echo 1048576 > /proc/sys/net/core/wmem_max	
echo 524288 > /proc/sys/net/core/wmem_default 

echo 2 > /proc/sys/net/ipv4/tcp_early_retrans

touch /tmp/enc2app_data
touch /tmp/enc2app_cmd
touch /tmp/cmd_shmarea
touch /tmp/myencodemsg

insmod /usr/lib/modules/ambarella_eth.ko

insmod /usr/lib/modules/osa.ko
insmod /usr/lib/modules/log.ko
insmod /usr/lib/modules/binder.ko r0size=1020 r2size=1020

insmod /usr/lib/modules/spf.ko

insmod /usr/lib/modules/prc.ko

APPAUTO=1
CMDLINE="/proc/dahua/bootpara"
APPAUTO=`cat /proc/dahua/bootpara`
APPAUTO=${APPAUTO##*appauto:}
APPAUTO=${APPAUTO%%dh_keyboard*}
if [  $APPAUTO == '1' -a -e "/mnt/mtd/Config/clearparam" -a ! -e "/mnt/mtd/powerup" ]
then
	TEST=`cat /mnt/mtd/Config/clearparam`
	if [ "$TEST" = "paramClear" ]
	then
		insmod /usr/lib/modules/pdc.ko
		ln -s /usr/sbin/systools /tmp/backupd
		/tmp/backupd &
		clearparam
	else
		rm -f /mnt/mtd/Config/clearparam
	fi
fi

if [  $APPAUTO == '1' -a -e "/mnt/mtd/Config_bak" ]
then
	rm -rf /mnt/mtd/Config
	rm -rf /mnt/mtd/backup/*
	mv -f /mnt/mtd/Config_bak /mnt/mtd/Config
	mkdir -p /mnt/mtd/Config /mnt/mtd/Log /mnt/backup/Config /mnt/mtd/Config/ppp
	mkdir -p /mnt/backup/debug
	mkdir -p /var/tmp/autoFix

	touch /mnt/mtd/Config/ppp/options
	touch /mnt/mtd/Config/ppp/pppoe-enable
	touch /mnt/mtd/Config/ppp/pap-secrets
	touch /mnt/mtd/Config/ppp/pppoesessionctx
	touch /mnt/mtd/Config/ppp/pppoe-redial_time
	touch /mnt/mtd/Config/dial-ip
	touch /mnt/mtd/powerup
	sync
fi

insmod /usr/lib/modules/pdc.ko gBaseline=240 sdk=260

STRING=$(gethwid 2)
temp=${STRING##*hwidValue == }
CATEGORY=${temp%% *}
echo CATEGORY = $CATEGORY 

if [ $CATEGORY -eq 3 ];then
	echo "SD Device"
	/usr/etc/SDimod
else
	echo "IPC Device"
	insmod /usr/lib/modules/crypt.ko
	/usr/etc/IPCimod
fi

