#! /bin/sh
ifconfig lo up
netinit if=eth0 default
netinit6 if=eth0

/sbin/syshelper 60 &
#/usr/sbin/upgraded &


insmod /usr/lib/modules/sensor.ko

insmod /usr/lib/modules/ivf.ko size=506

#加载amba驱动
insmod /usr/lib/modules/amba_video.ko


cap_fast=""
quickstart=$(cat /proc/dahua/bootpara | grep quickstart)
temp=${quickstart##*quickstart:}
quickstart_value=${temp%% *}

if [ $quickstart_value -eq 1 ];then
	cap_fast="FAST"
fi
echo cap_fast = $cap_fast
#安装sd卡驱动
if [ "$cap_fast" != "FAST" ];then
	insmod /usr/lib/modules/sdcard.ko
fi


mknod /dev/fdet c 248 148
mknod /dev/ambad c 248 248
mknod /dev/dsplog c 248 249

/usr/sbin/load_ucode /usr/lib/firmware
case "$?" in
	0)
	;;
	*)
  	echo "Load ucode failed!"
	exit 1
	;;
esac

#读取完整的HWID
HWID=$(armbenv -r HWID | grep HWID)
temp=${HWID##*HWID = }
hwid_value=${temp%% *}
echo hwid_value =$hwid_value

#解析设备名称和前端类型
PRODUCT=$(gethwid 0)
temp=${PRODUCT##*hwidValue == }
product_name=${temp%% *}
echo product_name =$product_name

# 安装网卡驱动
if [ "$product_name" = "IPC-KW10W-0280B-ZH" ];then
	rmmod  /usr/lib/modules/ambarella_eth.ko
	
	echo  device  >  /proc/ambarella/usbphy0
	insmod /usr/lib/modules/udc-core.ko
	insmod /usr/lib/modules/ambarella_udc.ko
	insmod /usr/lib/modules/libcomposite.ko
	#insmod /usr/lib/modules/g_ether.ko
fi

#解析镜头类型
LENSTYPE=$(gethwid 19)
temp=${LENSTYPE##*hwidValue == }
lens_type=${temp%% *}
echo lens_type =$lens_type


STRSEN=$(gethwid 4)
temp=${STRSEN##*hwidValue == }
fvideo_chip=${temp%% *}
echo fvideo_chip = $fvideo_chip

#是否支持模拟输出
cap_vout="TVOUT"
VOUTSUPPORT=$(gethwid 16)
echo $VOUTSUPPORT
temp=${VOUTSUPPORT##*hwidValue == }
vout_support=${temp%% *}
echo vout_support =$vout_support
if [ $vout_support -eq 0 ];then
	cap_vout=""
fi
echo cap_vout = $cap_vout

#mp_autotest环境变量只在初次烧片或者设备没有该环境变量的情况下，使用代码中配置的默认值
#同时清除mp_autotest环境变量或使其值为0方可出货
mp_autotest=`cat /dev/mtdblock2  | grep mp_autotest`	 
temp=${mp_autotest##*mp_autotest=}
mp_autotest_flag=${temp%% *}

DSPCHIP=$(gethwid 5)
temp=${DSPCHIP##*hwidValue == }
dspChip=${temp%% *}
echo dspChip = $dspChip

S3LM=0
if [ $dspChip -eq 33 -o $dspChip -eq 32 -o $dspChip -eq 37 -o $dspChip -eq 41 ] ;then
	S3LM=1
fi
echo S3LM= $S3LM
if [ $S3LM -eq 1 ] ;then
SYSBACKUP=$(armbenv -r sysbackup | grep sysbackup)
temp=${SYSBACKUP##*sysbackup = }
sysbackup_value=${temp%% *}
echo sysbackup_value =$sysbackup_value
if [ "$sysbackup_value" = "1" ];then
ln -s /usr/sbin/systools /tmp/backupd 
/tmp/backupd &
fi
fi
if [ $S3LM -eq 1 -a $vout_support -eq 0 ] ;then
echo "close cvbs and vout"
#不带模拟输出的设备,关闭cvbs以及tvout,降功耗
/usr/bin/data/amba_debug -w 0xec170164 -d 0x08234120
/usr/bin/data/amba_debug -w 0xec1700c0 -d 0x01278120
fi

#关闭vin mclk
cap_closemclk=0;
case "$product_name" in
        "IPC-HDPW4238-WPT-SA" | "IPC-HDPW4233-PT-SA" | "IPC-HDPW4436-WPT-SA" | "IPC-HDPW4431-PT-SA")
        	cap_closemclk=1
        	;;
esac
if [ "$cap_closemclk" = "1" ];then
/usr/bin/data/amba_debug -w 0xec1700bc -d 0x1
fi

#sd卡是USB接口
cap_usbsd=0;
case "$product_name" in
        "IPC-HFW2235M-W4G-AS" | "IPC-HFW2235M-W-S" | "IPC-HFW2231MP-4G-AS" | "IPC-HFW2235M-W4G-S")
        	cap_usbsd=1
        	;;
esac

if [ "$cap_usbsd" = "1" ];then
	insmod /usr/lib/modules/scsi_mod.ko
	insmod /usr/lib/modules/sd_mod.ko
	insmod /usr/lib/modules/usb-storage.ko
fi

if [ $S3LM -eq 1 ];then
echo "start sshd"
mkdir -p /var/empty/sshd
chown root:root /var/empty/sshd
chmod 755 /var/empty/sshd
/usr/local/sbin/sshd&
fi

AUTIOIN=$(gethwid 9)
temp=${AUTIOIN##*hwidValue == }
audioin=${temp%% *}
echo audioin = $audioin

SENSORID=$(gethwid 4)
temp=${SENSORID##*hwidValue == }
sensor_id=${temp%% *}
echo sensor_id $sensor_id

#根据设备型号确定驱动加载能力
cap_af=""
cap_wifi=0
cap_3g=0
cap_usb_net=0
cap_bluetooth=0
cap_usb_camera=0
case "$product_name" in
	"IPC-RM26" | "IPC-RM26-4G" | "IPC-RM26-V2" | "IPC-RM26-4G-V2" )
		cap_usb_net=1
		cap_bluetooth=1
		cap_usb_camera=1
		;;
esac
case "$product_name" in
        "IPC-KW100W" | "IPC-KW100W-R" | "IPC-K200W" | "DH-CE-TP1S")
        	cap_wifi=1
        	;;
esac

case "$product_name" in
        "IPC-HFW7226F-W4G" | "IPC-K15-LTE" | "IPC-K35-LTE")
        	cap_3g=1
        	;;
        "IPC-HFW2235M-W4G-AS" | "IPC-RM26-4G" | "IPC-HFW2231MP-4G-AS" | "IPC-RM26-4G-V2" | "IPC-HFW2235M-W4G-S")
        	cap_3g=2
        	;;
esac

WIFI=$(gethwid 14)
temp=${WIFI##*hwidValue == }
wifi=${temp%% *}
echo wifi = $wifi

if [ "$wifi" = "0" ];then
	cap_wifi=0
	echo ------cap_wifi = $cap_wifi
else
	cap_wifi=1
    echo ******cap_wifi = $cap_wifi
fi

case "$product_name" in

        "IPC-AW13W" | "IPC-HFW7226F-W4G" | "IPC-HFW7226F-WS" | "IPC-AW25W-Amcrest" | "IPC-AW25W-V2-Amcrest" | "IPC-AW15W-Amcrest" | "IPC-C15" | \
		"IPC-C35" | "IPC-K15" | "IPC-K35" | "IPC-HDBW1120E-W" | "IPC-HDBW1320E-W" | "IPC-HDBW1120E-AW" | "IPC-HDBW1320E-AW" | "IPC-A35-H" | \
		"IPC-A15" | "IPC-A15-H" | "IPC-C15-CE" | "IPC-EW4431-ASW" | "IPC-EW4431-SW" | "IPC-EW5431-ASW" | "IPC-EW5431-SW" | "IPC-TA25" | "IPC-HDBW4233R-S2" |  \
		"IPC-HFW1235S-W" | "IPC-HFW1435S-W" | "IPC-HDBW1230E-AW" | "IPC-HDBW1430E-AW" | "IPC-HDBW1235E-W" | "IPC-HDBW1435E-W" | "IPC-HDBW1430SN-AW-Lexus" | "IPC-HFW1430SN-W-Lexus" | "IPC-HDBW1235E-W-Lexus" | "IPC-HFW1235S-W-Lexus"|\
		"IPC-K86" |"IPC-TF26" |"IPC-K26" | "IPC-K46" | "IPC-TK26" |"IPC-TK15" | "IPC-A26" | "IPC-A46" | "IPC-A46L" | "IPC-C26" | "IPC-C46" | "IPC-HDPW4238-WPT-SA" | "IPC-HDPW4436-WPT-SA" | \
		"CE-TC5S" | "IPC-A26G" | "IPC-A46G" | "IPC-A46-Diamond" | "IPC-A26-Diamond" | "IPC-HFW2235M-W4G-AS" | "IPC-HFW2235M-W-S" | "IPC-HFW2235M-W4G-S")
        	cap_wifi=2
        	;;
		"IPC-C35-Amcrest" | "IPC-AW25W-5G" | "IPC-AW15W-5G" | "IPC-K15-5G" | "IPC-K35-5G" | "IPC-AW35W-5G" | "IPC-AW46W-5G")
        	cap_wifi=6
        	;;
    "IPC-HDP4231G" | "IPC-HDP4431G" | "IPC-A26Z" | "IPC-A46Z")
    			cap_wifi=4
        	;;
	"IPC-RM26-4G" | "IPC-RM26" | "IPC-RM26-4G-V2" | "IPC-RM26-V2")
    			cap_wifi=7
        	;;
    "IPC-TA26")
        cap_wifi=8
			;;
	"IPC-HFW4631K-AS-WS" | "IPC-HFW4233K-AS-WS")
        cap_wifi=9
			;;
esac

if [ $cap_wifi -eq 1 ];then
	echo host > /proc/ambarella/usbphy0                     #将设备的usb设置成host模式
	sleep 1
	insmod /usr/lib/modules/Wireless/AR9271STA/cfg80211.ko
	insmod /usr/lib/modules/Wireless/AR9271STA/mac80211.ko
	insmod /usr/lib/modules/Wireless/AR9271STA/ath9k_htc.ko
fi

if [ $cap_wifi -eq 2 ];then
	echo host > /proc/ambarella/usbphy0                     #将设备的usb设置成host模式
	#USB切换到host模式之后读取设备描述需要时间,加载驱动会对wifi下电操作影响设备描述读取
	sleep 1
    insmod /usr/lib/modules/8188eu.ko rtw_channel_plan=0x05

fi

if [ $cap_wifi -eq 4 ];then                                 #加载8811驱动
	echo host > /proc/ambarella/usbphy0                     #将设备的usb设置成host模式
	#USB切换到host模式之后读取设备描述需要时间,加载驱动会对wifi下电操作影响设备描述读取
	sleep 1
	insmod /usr/lib/modules/Wireless/compat.ko
	insmod /usr/lib/modules/Wireless/cfg80211.ko
	insmod /usr/lib/modules/8811au.ko
fi

if [ $cap_wifi -eq 5 ];then                                 #加载9377驱动
	echo host > /proc/ambarella/usbphy0                     #将设备的usb设置成host模式
	#USB切换到host模式之后读取设备描述需要时间,加载驱动会对wifi下电操作影响设备描述读取
	sleep 1
	insmod /usr/lib/modules/Wireless/compat.ko
	insmod /usr/lib/modules/Wireless/cfg80211.ko
	insmod /usr/lib/modules/Wireless/wlan.ko
fi

if [ $cap_wifi -eq 6 ];then                                 #8811与9377 驱动
	echo host > /proc/ambarella/usbphy0                     #将设备的usb设置成host模式
	#USB切换到host模式之后读取设备描述需要时间,加载驱动会对wifi下电操作影响设备描述读取
	sleep 1
	insmod /usr/lib/modules/Wireless/compat.ko
	insmod /usr/lib/modules/Wireless/cfg80211.ko
	insmod /usr/lib/modules/Wireless/wlan.ko
    insmod /usr/lib/modules/8811au.ko
fi

if [ $cap_wifi -eq 7 ];then                                 #加载9377驱动,SDIO接口
	sleep 1
	insmod /usr/lib/modules/Wireless/compat.ko
	insmod /usr/lib/modules/Wireless/cfg80211.ko
	insmod /usr/lib/modules/Wireless/wlan.ko ifname=eth2 
fi

if [ $cap_wifi -eq 8 ];then                                 #加载8189es驱动, SDIO接口
	insmod /usr/lib/modules/8189es.ko rtw_channel_plan=0x05
fi

if [ $cap_wifi -eq 9 ];then                                 #加载9377驱动,USB接口
	echo host > /proc/ambarella/usbphy0                     #将设备的usb设置成host模式
	#USB切换到host模式之后读取设备描述需要时间,加载驱动会对wifi下电操作影响设备描述读取
	sleep 1
	insmod /usr/lib/modules/Wireless/compat.ko
	insmod /usr/lib/modules/Wireless/cfg80211.ko
	insmod /usr/lib/modules/8811au.ko
	insmod /usr/lib/modules/Wireless/wlan.ko ifname=wlan1
fi

#USB摄像头
if [ $cap_usb_camera -eq 1 ]; then
	echo host > /proc/ambarella/usbphy0
	sleep 1
	insmod /usr/lib/modules/videodev.ko
	insmod /usr/lib/modules/videobuf2-core.ko
	insmod /usr/lib/modules/videobuf2-memops.ko
	insmod /usr/lib/modules/videobuf2-vmalloc.ko
	insmod /usr/lib/modules/uvcvideo.ko
fi
#USB网卡
if [ $cap_usb_net -eq 1 ]; then
	echo host > /proc/ambarella/usbphy0
	sleep 1
	insmod /usr/lib/modules/usbnet.ko
	insmod /usr/lib/modules/asix.ko
	insmod /usr/lib/modules/ax88179_178a.ko
	netinit if=eth0 default
fi
#简单云台设备定义
isSimplifiedPtz=0
ckTimePoint=0
cap_motor=""
case "$product_name" in

        "IPC-HFW4103E" | "IPC-HFW4203D" | "IPC-HFW5120E-Z" | "IPC-HFW5120D-Z" | "IPC-HFW5220D-Z" | "IPC-HDBW5120E-Z" | "IPC-HDBW5120EP-Z" | "IPC-HDBW5121E-Z" | "IPC-HDB5121E-Z" | "IPC-HDBW5121EP-Z" | "IPC-HDBW5220E-Z" | "IPC-HDBW5220EP-Z" | "IPC-HDBW5221E-Z" | "IPC-HDB5221E-Z" | "IPC-HDBW5221EP-Z" | "IPC-HDBW5421E-Z" | "IPC-HDB5421E-Z" | "IPC-HDBW5421EP-Z" | "IPC-HDW2120R-Z" | "IPC-HDW2220R-Z" | "IPC-HFW5121E-Z" | "IPC-HFW5220E-Z" | "IPC-HFW5221E-Z" | "IPC-HFW5121D-Z" | "IPC-HFW5221D-Z" | "IPC-HFW5421E-Z" | "IPC-HFW5421D-Z" | "IPC-HF5120E" | "IPC-HF5121E" | "IPC-HF5220E" | "IPC-HF5221E" | "IPC-HF5421E" | "IPC-HFW5121E-ZH" | "IPC-HFW5220E-ZH" | "IPC-HFW5221E-ZH" | "IPC-HFW5421E-ZH" | "IPC-HFW5121E-CA-IRA" | "IPC-HFW5221E-CA-IRA" | "IPC-HFW5221D-CA" | "IPC-HDW4120R-Z" | "IPC-HDW4220R-Z" | "IPC-HDW2320R-Z" | \
		"IPC-HDBW5121EP-ZH" | "IPC-HDBW5221EP-ZH" | "IPC-HDBW5220EP-ZH" | "IPC-HDBW5421EP-ZH" | "IPC-HDBW5121E-ZH" | "IPC-HDBW5221E-ZH" | "IPC-HDBW5421E-ZH" | "IPC-HFW2120R-ZS" | "IPC-HFW2220R-ZS" | "IPC-HFW2320R-ZS" | "IPC-HFW2421R-ZS" | "IPC-HDBW2120R-ZS" | "IPC-HDBW2220R-ZS" | "IPC-HDBW2320R-ZS" | "IPC-HF5121E-A2" | "IPC-HF5221E-A2" | "IPC-HF5421E-A2" | "IPC-HFW5421E-CA-IRA" | \
		"IPC-HFW4120R-ZAS" | "IPC-HFW4120R-Z" | "IPC-HFW4220R-ZAS" | "IPC-HFW4220R-Z" | "IPC-HFW8321EN-Z" | "IPC-HFW8221EN-Z" | "IPC-HDBW2320R-ZAS" | "IPC-HDBW8321EN-Z" | "IPC-HDBW8221EN-Z" | \
		"IPC-HDBW5121E-Z-A2" | "IPC-HDBW5221E-Z-A2" | "IPC-HDBW5421E-Z-A2" | "IPC-HFW2320R-Z" | "IPC-HF5231E" | "IPC-HF5431E" | \
		"IPC-HFW5231E-Z" | "IPC-HFW5431E-Z" | "IPC-HDW5231R-Z" | "IPC-HDW5431R-Z" | "IPC-HDBW5231R-Z" | "IPC-HDBW5431R-Z" | "IPC-HDBW5231EP-Z-S2" | "IPC-HDBW5431EP-Z-S2" | "IPC-HDBW5231E-Z-S2" | "IPC-HDBW5431E-Z-S2" | "IPC-HDBW5830R" | \
		"IPC-HFW5231E-Z-0735" | "IPC-HFW5431E-Z-0735" | "IPC-HFW5830E-Z-0735" | "IPC-HFW5830E-Z" | "IPC-HFW5830E-ZH-0735" | "IPC-HFW5830E-ZH" | "IPC-HDW5830R-Z" | "IPC-HDBW5231EP-Z-0735-S2" | "IPC-HDBW5431EP-Z-0735-S2" | \
		"IPC-HDBW5231E-Z-0735-S2" | "IPC-HDBW5431E-Z-0735-S2" | "IPC-HDBW5830EP-Z-0735-S2" | "IPC-HDBW5830EP-Z-S2" | "IPC-HDBW5830EP-ZH-0735-S2" | "IPC-HDBW5830EP-ZH-S2"| "IPC-HDBW5830E-Z-0735-S2" | "IPC-HDBW5830E-Z-S2" | "IPC-HDBW5830E-ZH-0735-S2" | "IPC-HDBW5830E-ZH-S2" |  "IPC-HDW2231RP-ZS" | "IPC-HDW2230RP-ZS" | \
		"IPC-HDW2431RP-ZS" | "IPC-HFW2230R-ZS" | "IPC-HFW2231R-ZS" | "IPC-HFW2431R-ZS" | "IPC-HDBW2231R-Z" | "IPC-HDBW2431R-Z" | "IPC-HDBW2230R-Z" | \
		"IPC-HFW2121R-ZS" | "IPC-HFW2221R-ZS" | "IPC-HFW2421R-ZS" | "IPC-HFW5231E-Z12-S2" | "IPC-HDBW5231EP-ZH-S2" | "IPC-HDBW5431EP-ZH-S2" | "IPC-HFW5231E-ZH" | "IPC-HFW5431E-ZH" | \
		"IPC-HDBW2231R-Z-2713" | "IPC-HDBW2431R-Z-2713" | "IPC-HDBW2230R-Z-2713" | "IPC-HFW2230R-ZS-2713" | "IPC-HFW2231R-ZS-2713" | "IPC-HFW2431R-ZS-2713" | "IPC-HDW2231RP-ZS-2713" | "IPC-HDW2230RP-ZS-2713" | "IPC-HDW2431RP-ZS-2713" | \
		"IPC-HDW5231R-Z-2713" | "IPC-HDW5431R-Z-2713" | "IPC-HFW5231E-Z-2713" | "IPC-HFW5431E-Z-2713" | "IPC-HFW5231E-ZH-2713" | "IPC-HFW5431E-ZH-2713" | "IPC-HDBW5231EP-Z-S2-2713" | "IPC-HDBW5231EP-ZH-S2-2713" | "IPC-HDBW5431EP-Z-S2-2713" | "IPC-HDBW5431EP-ZH-S2-2713" | \
		"IPC-HDBW5631R-ZS" | "IPC-HDBW5631R-ZAS" | "IPC-HDBW5631RP-Z" | "IPC-HDBW5631RP-Z-2713" | "IPC-HFW5631E-Z" | "IPC-HFW5631E-ZH" | "IPC-HFW5631E-Z-2713" | "IPC-HFW5631E-ZH-2713" | "IPC-HFW5631E-Z-IRA" | "IPC-HFW5631K-Z-I4" | "IPC-HFW4631R-ZS" | "IPC-HFW4631R-ZAS" | "IPC-HFW5631E-Z-IRA-2713" | \
		"IPC-HFW5631K-Z-I4-2713" | "IPC-HDBW5830EP-Z-S2-2713" | "IPC-HDBW5830EP-ZH-S2-2713" | "IPC-HDBW5631EP-Z-S2" | "IPC-HDBW5631EP-ZH-S2" | "IPC-HDBW5631E-Z" | "IPC-HDW5631RP-Z-S2" | "IPC-HDBW5631EP-Z-S2-2713" | "IPC-HDBW5631EP-ZH-S2-2713" | "IPC-HDBW5631E-Z-2713" | "IPC-HDW5631RP-Z-S2-2713" | \
		"IPC-HDBW5631EP-Z-0735-S2" | "IPC-HDBW5631EP-ZH-0735-S2" | "IPC-HDBW5631E-Z-0735" | "IPC-HFW5631E-Z-0735" | "IPC-HFW5631E-ZH-0735" | "IPC-HFW5631E-Z-IRA-0735" | "IPC-HFW5631K-Z-I4-0735" | "IPC-HF5631F" | \
		"IPC-HFW5631E-Z-27135" | "IPC-HFW5631E-Z-X-27135" | "IPC-HDBW5631E-Z-27135" | "IPC-HDBW5631E-Z-X-27135" | "IPC-HFW5631E-Z-IRA-27135" | "IPC-HFW5631K-Z-I4-27135" | "IPC-HFW5631E-Z-IRA-X-27135" | "IPC-HFW5631K-Z-I4-X-27135" | \
		"IPC-HFW4631F-ZS-27135" | "IPC-HFW4631F-ZAS-27135" | "IPC-HFW4631F-ZAS-X-27135" | "IPC-HDBW4631R-ZS-27135" | "IPC-HDBW4631R-ZAS-27135" | "IPC-HDBW4631R-ZAS-X-27135" | \
		"IPC-HDBW5631E-Z-X-0735" | "IPC-HFW5631E-Z-IRA-X-0735" | "IPC-HFW5631E-Z-X-0735" | "IPC-HFW5631K-Z-I4-X-0735" | "IPC-HDBW5231EP-ZH-0735-S2" | "IPC-HDBW5431EP-ZH-0735-S2" | "IPC-HFW5231EP-ZH-0735-S2" | "IPC-HFW5431EP-ZH-0735-S2" | \
		"IPC-HDB5631E-Z-27135" | "IPC-HDB5631E-Z-0735" | "IPC-HDB5631E-Z-X-27135" | "IPC-HDB5631E-Z-X-0735" | "IPC-HFW5631E-Z-IRA-27135-AC24" | "IPC-HFW5631E-Z-IRA-0735-AC24V" | \
		"IPC-HFW5631E-Z-IRA-X-27135-24V" | "IPC-HFW5631E-Z-IRA-X1-27135" | "IPC-HFW5631E-Z-27135-AC24V" | "IPC-HFW5631E-Z-0735-AC24V" | "IPC-HFW5631E-Z-X1-27135-AC24V" | "IPC-HFW5631E-Z-X1-0735-AC24V" | "IPC-HFW5631E-Z-27135-S3" | "IPC-HFW5631E-Z-0735-S3" | "IPC-HFW5631E-ZH-27135-S3" | "IPC-HFW5631E-ZH-0735-S3" | \
		"IPC-HDBW5231RP-Z-27135-S3" | "IPC-HDBW5431RP-Z-27135-S3" | "IPC-HDBW5830EP-Z-S3" | "IPC-HDBW5830EP-ZH-S3" | "IPC-HDBW5231EP-ZH-0735-S3" | "IPC-HDBW5231EP-Z-0735-S3" | "IPC-HDBW5431EP-ZH-0735-S3" | "IPC-HDBW5431EP-Z-0735-S3" | \
		"IPC-HDBW5830EP-Z-0735-S3" | "IPC-HDBW5830EP-ZH-0735-S3" | "IPC-HDW2531RP-ZS-27135-XW" | "IPC-HDW2531RP-ZS-27135" | "IPC-HFW2531R-ZS-IRE6-27135" | "IPC-HFW2531RP-ZAS-IRE6-27135" | "IPC-HDBW2531R-ZS-27135" | "IPC-HDBW2531R-ZAS-27135" | "IPC-HFW5631E-Z-IRA-27135-AC24V" | \
		"IPC-HFW5830E-Z-S3" | "IPC-HFW5830E-ZH-S3" | "IPC-HFW5231E-Z-0735-S3" | "IPC-HFW5431E-Z-0735-S3" | "IPC-HFW5830E-Z-0735-S3" | "IPC-HFW5231E-ZH-0735-S3" | "IPC-HFW5431E-ZH-0735-S3" | "IPC-HFW5830E-ZH-0735-S3" | "IPC-HFW5231E-Z-0560-S3" |\
		"IPC-HFW5631E-Z-27135-S3" | "IPC-HFW5631E-Z-0735-S3" | "IPC-HFW5631E-ZH-27135-S3" | "IPC-HFW5631E-ZH-0735-S3" | "IPC-HFW5631E-Z-IRA-X-0735-24V" | "IPC-HDW5830RP-Z-S2" | "IPC-HFW2230T-ZS-2713" | "IPC-HFW2231T-ZS-2713" | "IPC-HFW2431T-ZS-2713" | \
		"IPC-HFW2230T-ZAS-2713" | "IPC-HFW2231T-ZAS-2713" | "IPC-HFW2431T-ZAS-2713" | "IPC-HDBW5831GP-Z-2712-S3" | "IPC-HDBW5831GP-Z-0735-S3" | "IPC-HDBW5631GP-Z-27135-S3" | \
		"IPC-HDBW5631GP-Z-0735-S3" | "IPC-HDBW5431GP-Z-27135-S3" | "IPC-HDBW5431GP-Z-0735-S3" | "IPC-HDBW5231GP-Z-27135-S3" | "IPC-HDBW5231GP-Z-0735-S3" | "IPC-HFW5631K-Z-I4-27135-AC24V" | \
		"IPC-HFW5631K-Z-I4-0735-AC24V" | "IPC-HFW5631K-Z-I4-X-27135-AC24V" | "IPC-HFW5631K-Z-I4-X-0735-AC24V" | "IPC-HFW5233E-Z-27135" | "IPC-HFW5233K-Z-I2-27135" | "IPC-HFW5238E-Z-27135-S2" | "IPC-HFW5433E-Z-27135" | "IPC-HFW5433K-Z-I2-27135" | "IPC-HFW5438E-Z-27135-S2" | \
		"IPC-HFW5233E-Z-X1-27135" | "IPC-HFW5233K-Z-I2-X1-27135" | "IPC-HFW5233K-Z-I4-X1-0735" | "IPC-HFW5233E-Z-IRA-X1-0560" | "IPC-HFW5238E-Z-X1-27135-S2" | "IPC-HFW5433E-Z-X1-27135" | "IPC-HFW5433K-Z-I2-X1-27135" | "IPC-HFW5433K-Z-I4-X1-0735" | "IPC-HFW5433E-Z-IRA-X1-0560" | "IPC-HFW5438E-Z-X1-27135-S2" | \
	    "IPC-HDBW5233E-Z-27135" | "IPC-HDB5233E-Z-27135" | "IPC-HDBW5238E-Z-27135-S2" | "IPC-HDBW5433E-Z-27135" | "IPC-HDB5238E-Z-27135-S2" | "IPC-HDB5433E-Z-27135" | "IPC-HDBW5233E-Z-X1-27135" | "IPC-HDB5233E-Z-X1-27135" | "IPC-HDBW5433E-Z-X1-27135" | "IPC-HDB5433E-Z-X1-27135" | "IPC-HDBW5438E-Z-27135" | "IPC-HDB5438E-Z-27135-S2" | "IPC-HDBW5238E-Z-X1-27135-S2" | "IPC-HDB5238E-Z-X1-27135-S2" | "IPC-HDBW5438E-Z-X1-27135-S2" | "IPC-HDB5438E-Z-X1-27135-S2" | \
	    "IPC-HF5433E" | "IPC-HF5433E-E" | "IPC-HF5233E" | "IPC-HF5233E-E" | "IPC-HDBW5231EP-ZE-HDMI-27135" |\
		"IPC-HFW5238E-Z-27135-S2" | "IPC-HFW5438E-Z-27135-S2" | "IPC-HFW5238E-Z-X1-27135-S2" | "IPC-HFW5438E-Z-X1-27135-S2" | "IPC-HDBW5238E-Z-27135-S2" | "IPC-HDB5238E-Z-27135-S2" |\
		"IPC-HDBW5438E-Z-27135" | "IPC-HDB5438E-Z-27135-S2" | "IPC-HDBW5238E-Z-X1-27135-S2" | "IPC-HDB5238E-Z-X1-27135-S2" | "IPC-HDBW5438E-Z-X1-27135-S2" | "IPC-HDB5438E-Z-X1-27135-S2" | \
		"IPC-HFW4431EP-Z-S4" | "IPC-HDBW4431E-Z-S4" | "IPC-HDW4431T-Z-S4" | "IPC-HFW4231EP-Z-S4" | "IPC-HDBW4231E-Z-S4" | "IPC-HDW4231T-Z-S4")
		cap_motor="MOTOR"
        	;;
		"IPC-AW15W-Amcrest" | "IPC-AW25W-Amcrest" | "IPC-AW25W-V2-Amcrest" | "IPC-AW25A-Amcrest" | "IPC-AW15A-Amcrest" | "IPC-AW15A-Amcrest-V2"| "IPC-AW25A-Amcrest-V2" | "IPC-AW25W-5G" | "IPC-AW15W-5G" | "IPC-AW35W-5G")
        	cap_motor="MOTOR"
                ptzPreset=PSF_AMCREST
			if [ "$fvideo_chip" = "46" ];then
				ptzcal=CAL_LS26F
				ptzcfg=CFG_AW15W
			else
				ptzcal=CAL_YT40F
				ptzcfg=CFG_AW25W_V2
			fi
        	;;
        "IPC-HDPW4431-PT-SA" | "IPC-HDPW4436-WPT-SA")
            cap_motor="MOTOR"
            ptzcal=CAL_YT1125_40F
            ptzcfg=CFG_HDPW44XX
			ckTimePoint=2
			isSimplifiedPtz=1
                ;;
        "IPC-HDPW4238-WPT-SA" | "IPC-HDPW4233-PT-SA")
            cap_motor="MOTOR"
            ptzcfg=CFG_HDPW42XX
            ptzcal=CAL_YT1125_40F
			ckTimePoint=2
			isSimplifiedPtz=1
                ;;
		"IPC-A26" | "IPC-A26G" | "IPC-A26-Diamond")
			cap_motor="MOTOR"
			ptzcal=CAL_YT40F
			ptzcfg=CFG_A26
			ckTimePoint=2
			;;
		"IPC-A46" | "IPC-A46G" | "IPC-A46-Diamond")
			cap_motor="MOTOR"
			ptzcal=CAL_YT40F
			ptzcfg=CFG_A46
			ckTimePoint=2
			;;
		"IPC-AW13W")
			cap_motor="MOTOR"
			ptzcal=CAL_14B36F
			ptzcfg=CFG_CE_TP1
			;;
		"IPC-A35" | "IPC-A35-H" | "IPC-TA25")
			cap_motor="MOTOR"
			ptzcal=CAL_YT40F
			ptzcfg=CFG_A35
			ckTimePoint=2
			;;
		"IPC-A15" | "IPC-A15-H")
			cap_motor="MOTOR"
			ptzcal=CAL_YT40F
			ptzcfg=CFG_A15
			ckTimePoint=2
			;;
		"IPC-TA26")
			cap_motor="MOTOR"
			ptzcal=CAL_YT40F
			ptzcfg=CFG_TA26
			ckTimePoint=2
			;;
		"IPC-A26Z")
			cap_motor="MOTOR"
			ptzcfg=CFG_A26
			ckTimePoint=2
			;;
		"IPC-A46Z")
			cap_motor="MOTOR"
			ptzcfg=CFG_A46
			ckTimePoint=2
			;;
		"IPC-AW46W-5G")
			ptzPreset=PSF_AW46W_5G
			cap_motor="MOTOR"
			ptzcfg=CFG_AW46W_5G
			ckTimePoint=2
			;;
esac

if [ "$cap_motor" != "" ];then
	insmod /usr/lib/modules/motorDrv.ko
	if [ $ckTimePoint -eq 2 ];then
		/usr/bin/motorDebug ptz startup &
	fi
fi

if [ "$mp_autotest_flag" != "1" ];then
#解压缩pd到tmp目录
unzip /mnt/pd/product.zip -d /var/tmp > /dev/null
fi

#解压缩2A参数到tmp目录
#unzip /usr/data/2Acfg.zip -d /var/tmp > /dev/null

cp -r /usr/data/2Acfg /var/tmp/2Acfg/

cp -r /usr/data/ptzcfg /var/tmp/ptzcfg/

cp  /usr/data/osd.bmp /var/tmp

#创建pd目录
mkdir -p /var/tmp/pd
if [ "$mp_autotest_flag" != "1" ];then
#将设备名映射文件拷贝的pd分区
cp -f /var/tmp/product/ProductTransform /var/tmp/pd/
else 
#将设备名映射文件拷贝的pd分区	 	 
cp -f /mnt/pd/product/ProductTransform /var/tmp/pd/	 	 
fi
cp -f /var/tmp/product/CustomTemplate /var/tmp/pd/
if [ ! -f /var/tmp/pd/DefaultAccount ];then
	cp -f /var/tmp/product/DefaultAccount /var/tmp/pd/
fi

#根据不同的设备类型拷贝pd文件和2A参数文件
#国内600W分辨率要求不一样，添加特殊标识
is600w=0
#列车400W设备默认码流要求不一样，添加特殊标识
isMBW400w=0
isMBW200w=0

#普列半球设备型号根据HWID区分
jtktype="0"
#特种型号中文不需要乐橙，英文需要easy4ip
noLechange=0
#根据设备型号确定需要用product下的哪个目录以及2Acfg下的哪个目录
case "$product_name" in
	
	"IPC-HF5121E" | "IPC-HF5121E-A2")
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HF5120E" )
		product=IPC-HF5121E
		aewcfg=IPC-HF5120E
		;;	
	"IPC-HF5221E" | "IPC-HF5221E-A2")
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HF5421E" | "IPC-HF5421E-A2")
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HFW4121B" | "IPC-HDBW4121F-S")
		product=IPC-HF4121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HFW4221B" | "IPC-HFW4221BH")
		product=IPC-HF4221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HFW4421B" | "IPC-HFW4421BH" | "IPC-HFW2421R-VFS" | "IPC-HFW2421R-ZS")
		product=IPC-HF4421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDPW1420F")
		product=IPC-HF2420R
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDBW4120E" | "IPC-HDBW4120F-S" | "IPC-HDBW4120EH" | "IPC-HDW4120E-AS" | "IPC-HFW4120R-VFAS" | "IPC-HFW4120R-VF" | "IPC-HDW4120C-A" | "IPC-HDBW4120R-VFAS")
		product=IPC-HF4121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HFW2120R-VFS")
		product=IPC-HF2120R
		aewcfg=IPC-HF5120E
		;;	
	"IPC-HDBW4220E" | "IPC-HDBW4220EH" | "IPC-HDW4220E-AS" | "IPC-HFW4220R-VFAS" | "IPC-HFW4220R-VF" | "IPC-HDW4220C-A")
		product=IPC-HF4221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HFW2220R-VFS")
		product=IPC-HF2220R
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDBW4421E" | "IPC-HDBW4421F-S" | "IPC-HDW4421E-AS" | "IPC-HDW4421C-A")
		product=IPC-HF4421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDB4421E" )
		product=IPC-HF4421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDB4120E" )
		product=IPC-HF4121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDBW4221E" | "IPC-HDBW4221F-S" | "IPC-HDW4221E-AS" | "IPC-HDW4221C-A")
		product=IPC-HF4221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HDPW4120FP-W" )
		product=IPC-HDPW4120FP-W
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDPW4220FP-W" )
		product=IPC-HDPW4221FP-W
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDPW4221FP-W" )
		product=IPC-HDPW4221FP-W
		aewcfg=IPC-HF5221E
	;;
	"IPC-HDBW7121F-M" )
		product=IPC-HF4121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HDBW7221F-M" | "IPC-HDBW7221F-MPC")
		product=IPC-HF4221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HDBW7421F-M" )
		product=IPC-HF4421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HF5220E" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDBW5121E" | "IPC-HFW5121D" | "IPC-HDPW5121E")
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HDBW5121E-Z" | "IPC-HDB5121E-Z" | "IPC-HDBW5121E-ZH" | "IPC-HDBW5121E-Z-A2")
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HDBW5121EP" )
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HDBW5121EP-Z" | "IPC-HDBW5121EP-ZH")
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HDBW5120E" | "IPC-HFW5120D" | "IPC-HFW5120E")
		product=IPC-HF5121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDBW5120E-Z" | "IPC-HFW5120D-Z" | "IPC-HFW5120E-Z")
		product=IPC-HF5121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDBW5120EP" )
		product=IPC-HF5121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDBW5120EP-Z" )
		product=IPC-HF5121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDBW5221E" | "IPC-HFW5221D" | "IPC-HDB5221E-Z" | "IPC-HDPW5221E")
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HDBW5221E-Z" | "IPC-HDBW5221E-ZH" | "IPC-HDBW5221E-Z-A2")
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HDBW5221EP" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HDBW5221EP-Z" | "IPC-HDBW5221EP-ZH")
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HDBW5220E" | "IPC-HFW5220D" | "IPC-HFW5220E")
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDBW5220E-Z" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDBW5220EP" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDBW5220EP-Z" | "IPC-HDBW5220EP-ZH")
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HDBW5421E" | "IPC-HFW5421D" | "IPC-HDB5421E" | "IPC-HDP5421E" | "IPC-HDPW5421E")
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDBW5421E-Z" | "IPC-HDB5421E-Z" | "IPC-HDBW5421E-ZH" | "IPC-HDBW5421E-Z-A2")
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDBW5421EP" )
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDBW5421EP-Z" | "IPC-HDBW5421EP-ZH")
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HFW5121D-Z" )
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HFW5121E-IRA" )
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HFW5121E-Z" | "IPC-HFW5121E-ZH")
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HFW5221D-Z" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HFW5221E-IRA" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HFW5221E-Z" | "IPC-HFW5221E-ZH")
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HFW5220E-Z" | "IPC-HFW5220E-ZH")
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HFW5220D-Z" )
		product=IPC-HF5221E
		aewcfg=IPC-HF5220E
		;;
	"IPC-HFW5421D-Z" )
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HFW5421E-IRA" | "IPC-HFW5421E-CA-IRA")
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HFW5421E-Z" | "IPC-HFW5421E-ZH")
		product=IPC-HF5421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDW4120R-Z" | "IPC-HFW4120R-ZAS" | "IPC-HFW4120R-Z")
		product=IPC-HF4121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDW2120R-Z" | "IPC-HFW2120R-ZS" | "IPC-HFW4120R-Z" | IPC-HDBW2120R-ZS)
		product=IPC-HF2120R
		aewcfg=IPC-HF5120E
		;;	
	"IPC-HDW4220R-Z" | "IPC-HFW4220R-ZAS" | "IPC-HFW4220R-Z")
		product=IPC-HF4221E
		aewcfg=IPC-HF5220E
		;;		
	"IPC-HDW2220R-Z" |  "IPC-HFW2220R-ZS" | "IPC-HDBW2220R-ZS" | "IPC-HFW4220R-Z")
		product=IPC-HF2220R
		aewcfg=IPC-HF5220E
		;;
	"IPC-HFW1220R" )
		product=IPC-HF2220R
		aewcfg=IPC-HF5221E
		;;
	"IPC-HFW1420R"  | "IPC-HFW2420R-VFS" | "IPC-HFW2420R-ZS")
		product=IPC-HF2420R
		aewcfg=IPC-HF5421E
		;;
	"IPC-HDB4100R" )
		product=IPC-HF4121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-HDB4300R" )
		product=IPC-HF4421E
		aewcfg=IPC-HF5421E
		;;
	"IPC-EW5500E" )
		product=IPC-EW5500E
		aewcfg=IPC-EW5500E
		;;		
	"IPC-HFW4521S" )
		product=IPC-HFW4521S
		aewcfg=IPC-HFW4521S
		;;	
	"IPC-HD1320C" | "IPC-HDW1320S" | "IPC-HFW2320R-VFS")
		product=IPC-HF2320R
		aewcfg=IPC-HFW4320B
		;;	
	"IPC-HFW4320B")
		product=IPC-HFW4320B
		aewcfg=IPC-HFW4320B
		;;
	"IPC-HDB5121E" | "IPC-HDP5121E" | "IPC-HFW5121E-CA-IRA")
		product=IPC-HF5121E
		aewcfg=IPC-HF5121E
		;;
	"IPC-HDB5221E" | "IPC-HDP5221E")
		product=IPC-HF5221E
		aewcfg=IPC-HF5221E
		;;
	"IPC-HFW5221E-CA-IRA" | "IPC-HFW5221D-CA")
		product=IPC-HF5221E
		aewcfg=IPC-HFW5221E-CA-IRA
		;;
	"IPC-HDW2320R-Z" | "IPC-HFW2320R-ZS" | "IPC-HDBW2320R-ZS" | "IPC-HDBW2320R-ZAS" | "IPC-HFW2320R-Z")
		product=IPC-HF2320R
		aewcfg=IPC-HFW4320B
		;;
	"IPC-HDB5105H-JT" | "IPC-TDCZ02" | "IPC-HDB5105-JT-0600B" | "IPC-HDBW5105-JT-0600B")
		product=IPC-HF5121E
		aewcfg=IPC-HF5120E
		;;
	"IPC-KW10W-0280B-ZH" )
		product=IPC-KW10W
		aewcfg=IPC-HF5120E
		;;
	"IPC-AW13W" )
		product=IPC-AW13W
		aewcfg=IPC-AW13W
		;;
	"IPC-HFW8321EN-Z" | "IPC-HDBW8321EN-Z" )
		product=IPC-HFW8321EN-Z
		aewcfg=IPC-HFW8321E
		;;
	"IPC-HFW8221EN-Z" | "IPC-HDBW8221EN-Z" )
		product=IPC-HFW8221EN-Z
		aewcfg=IPC-HFW8221E
		;;
	"IPC-AW15W-Amcrest" | "IPC-AW15A-Amcrest" | "IPC-AW15A-Amcrest-V2" | "IPC-AW15W-5G")
		product=IPC-AW15W
		aewcfg=IPC-AW13W
		;;
	"IPC-AW25W-Amcrest" | "IPC-AW25W-V2-Amcrest" | "IPC-AW25A-Amcrest" | "IPC-AW25A-Amcrest-V2" | "IPC-AW25W-5G")
		if [ "$fvideo_chip" = "79" ];then
			product=IPC-AW25W
			aewcfg=IPC-IMX323
		else
			product=IPC-AW25W
			aewcfg=IPC-HF5220E
		fi
		;;
	"IPC-AW35W-5G")
		product=IPC-AW35W-5G
		aewcfg=IPC-HFW4320B
		;;
	"IPC-HFW7226F-W4G" )
		product=IPC-HFW7226F
		aewcfg=IPC-HF5221E
		;;
	"IPC-C35-Amcrest")
		product=IPC-AW35W-5G
		aewcfg=IPC-HFW4320B
		;;
	"IPC-C15-Amcrest")
		product=IPC-C15-AMCREST
		aewcfg=IPC-C15
		;;
	"IPC-HFW7226F-WS" )
		product=IPC-HFW7226F-WS
		aewcfg=IPC-HF5221E
		;;
	"IPC-C15")
		product=IPC-C15
		aewcfg=IPC-C15
		;;
	"IPC-C15-CE")
		product=IPC-C15-CE
		aewcfg=IPC-C15
		;;
	"IPC-C35")
		product=IPC-C35
		aewcfg=IPC-HFW4320B
		;;
	"IPC-K15" | "IPC-K15-5G")
		product=IPC-K15
		aewcfg=IPC-C15
		;;
	"IPC-TK15")
		product=IPC-K15-CE
		aewcfg=IPC-C15
		;;
	"IPC-TF26")
		product=IPC-TF26
		aewcfg=IPC-TF26
		;;		
	"IPC-K26")
		product=IPC-ACK-K26
		aewcfg=IPC-TF26		
		;;
	"IPC-HFW1235S-W" | "IPC-HDBW1230E-AW" | "IPC-HDBW1235E-W" )
		product=IPC-HF2231R-W
		aewcfg=IPC-TF26
		;;
	"IPC-TK26")
		product=IPC-ACK-TK26
		aewcfg=IPC-TF26	
		;;
	"IPC-A26")
		product=IPC-ACK-A26
		aewcfg=IPC-TF26		
		;;
	"IPC-A26Z" )
		product=IPC-ACK-A26Z
		aewcfg=IPC-A26Z
		;;
	"IPC-A26G")
		product=IPC-ACK-A26G
		aewcfg=IPC-TF26
		;;
	"IPC-A26-Diamond")
		product=IPC-ACK-A26-Diamond
		aewcfg=IPC-TF26
		;;
	"IPC-C26")
		product=IPC-ACK-C26
		aewcfg=IPC-TF26	
		;;
	"IPC-K46")
		product=IPC-ACK-K46
		aewcfg=IPC-HF5431E		
		;;
	"IPC-A46" | "IPC-A46L")
		product=IPC-ACK-A46
		aewcfg=IPC-HF5431E 		
		;;
	"IPC-A46Z" )
		product=IPC-ACK-A46Z
		aewcfg=IPC-HF5431E
		;;
	"IPC-A46G")
		product=IPC-ACK-A46G
		aewcfg=IPC-HF5431E
		;;
	"IPC-A46-Diamond")
		product=IPC-ACK-A46-Diamond
		aewcfg=IPC-HF5431E
		;;
	"IPC-C46")
		product=IPC-ACK-C46
		aewcfg=IPC-HF5431E
		;;
	"IPC-HFW1435S-W" | "IPC-HDBW1430E-AW" | "IPC-HDBW1435E-W")	
		product=IPC-HF2431R
		aewcfg=IPC-HF5431E
		;;
	"IPC-HFW1430SN-W-Lexus" | "IPC-HDBW1430SN-AW-Lexus" | "IPC-HDBW1430EN-AS-Lexus")	
		product=IPC-HFW1430SN
		aewcfg=IPC-HF5431E
		;;
	"IPC-HFW1430SN-Lexus")	
		product=IPC-HFW1430SN-POE
		aewcfg=IPC-HF5431E
		;;
	"IPC-HFW1235S-W-Lexus" | "IPC-HFW1230S-Lexus" | "IPC-HDBW1235E-W-Lexus" | "IPC-HDBW1230E-S-Lexus")	
		product=IPC-HFW1230S
		aewcfg=IPC-TF26
		;;
	"IPC-HFW1230S-Lexus")
		product=IPC-HFW1230S-POE
		aewcfg=IPC-TF26
		;;
	"IPC-K86")
		product=IPC-ACK-K86
		aewcfg=IPC-HFW4830E
		;;
	"IPC-K35" | "IPC-K35-5G")
		product=IPC-K35
		aewcfg=IPC-HFW4320B
		;;
	"IPC-K15-LTE")
		product=IPC-K15-LTE
		aewcfg=IPC-C15
		;;
	"IPC-K35-LTE")
		product=IPC-K35-LTE
		aewcfg=IPC-HFW4320B
		;;
	"IPC-HDBW1120E-W" | "IPC-HDBW1120E-AW")
		product=IPC-K-HDBW1120
		aewcfg=IPC-C15
		;;
	"IPC-HDBW1320E-W" | "IPC-HDBW1320E-AW")
		product=IPC-K-HDBW1320
		aewcfg=IPC-HFW4320B
		;;
	"IPC-A35")
		product=IPC-A35
		aewcfg=IPC-HFW4320B
		;;
	"IPC-A35-H")
		product=IPC-A35-H
		aewcfg=IPC-HFW4320B
		;;
	"IPC-A15")
		product=IPC-A15
		aewcfg=IPC-C15
		;;
	"IPC-A15-H")
		product=IPC-A15-H
		aewcfg=IPC-C15
		;;
	"IPC-TA25")
	    product=IPC-TA25
	    aewcfg=IPC-HFW4320B
	    ;;
	"IPC-HF5231E")
		product=IPC-HF5231E
		case $sensor_id in
			74)
				aewcfg=IPC-HF5231E
				;;
			106)
				aewcfg=IPC-IMX307-REPLACE290
				;;
			118)
				aewcfg=IPC-IMX327-REPLACE290
				;;
			*)
				aewcfg=IPC-HF5231E
				;;
		esac
		;;
	"IPC-HDW5231R-Z")
		product=IPC-HF5231E
		aewcfg=IPC-HF5231E
		;;
	"IPC-HFW5231E-Z" | "IPC-HDBW5231EP-Z-S2" | "IPC-HDBW5231E-Z-S2" | "IPC-HDBW5231R-Z" | "IPC-HDBW5231EP-ZH-S2" | "IPC-HFW5231E-ZH" | "IPC-HDW5231R-Z-2713" | "IPC-HFW5231E-Z-2713" | "IPC-HFW5231E-ZH-2713" | "IPC-HDBW5231EP-Z-S2-2713" | "IPC-HDBW5231EP-ZH-S2-2713" | "IPC-HDBW5231RP-Z-27135-S3" | "IPC-HDBW5231GP-Z-27135-S3" | "IPC-HDBW5231EP-ZE-HDMI-27135" )
		product=IPC-HF5231E
		case $sensor_id in
			74)
				aewcfg=IPC-HF5231E
				;;
			106)
				aewcfg=IPC-IMX307-REPLACE290
				;;
			118)
				aewcfg=IPC-IMX327-REPLACE290
				;;
			*)
				aewcfg=IPC-HF5231E
				;;
		esac
		;;
	"IPC-HFW4231EP-Z-S4" | "IPC-HDBW4231E-Z-S4" | "IPC-HDW4231T-Z-S4" )
		product=IPC-HF5231E
		aewcfg=IPC-IMX307
		;;
	"IPC-HFW5231E-Z-0735" | "IPC-HDBW5231EP-Z-0735-S2" | "IPC-HDBW5231E-Z-0735-S2" | "IPC-HFW5231E-Z12-S2" | "IPC-HDBW5231EP-ZH-0735-S2" | "IPC-HFW5231EP-ZH-0735-S2" | "IPC-HDBW5231EP-ZH-0735-S3" | "IPC-HDBW5231EP-Z-0735-S3" |\
	"IPC-HFW5231E-Z-0735-S3" | "IPC-HFW5231E-ZH-0735-S3" | "IPC-HFW5231E-Z-0560-S3" | "IPC-HDBW5231GP-Z-0735-S3")
    product=IPC-HF5231E
		aewcfg=IPC-HFW5231E-Z-0735
		;;	
	"IPC-HF5431E" | "IPC-HDBW5431EP-Z-S2" | "IPC-HDBW5431E-Z-S2" | "IPC-HFW5431E-Z" | "IPC-HDW5431R-Z" | "IPC-HDBW5431R-Z" | "IPC-HDBW5431EP-ZH-S2" | "IPC-HFW5431E-ZH" | "IPC-HDW5431R-Z-2713" | \
	"IPC-HFW5431E-Z-2713" | "IPC-HFW5431E-ZH-2713" | "IPC-HDBW5431EP-Z-S2-2713" | "IPC-HDBW5431EP-ZH-S2-2713" | "IPC-HDBW5431RP-Z-27135-S3" | "IPC-HDBW5431GP-Z-27135-S3" | "IPC-HFW4431EP-Z-S4" | \
	"IPC-HDBW4431E-Z-S4" | "IPC-HDW4431T-Z-S4")
		product=IPC-HF5431E
		aewcfg=IPC-HF5431E
		;;
	"IPC-HFW5431E-Z-0735" | "IPC-HDBW5431EP-Z-0735-S2" | "IPC-HDBW5431E-Z-0735-S2" | "IPC-HDBW5431EP-ZH-0735-S2" | "IPC-HFW5431EP-ZH-0735-S2" | "IPC-HDBW5431EP-ZH-0735-S3" | "IPC-HDBW5431EP-Z-0735-S3" |\
	"IPC-HFW5431E-Z-0735-S3" | "IPC-HFW5431E-ZH-0735-S3" | "IPC-HDBW5431GP-Z-0735-S3")
	  product=IPC-HF5431E
		aewcfg=IPC-HFW5431E-Z-0735
		;;	
	"IPC-HDBW4830EP-AS" | "IPC-HFW4830EP-S" | "IPC-HDW4830EM" | "IPC-HFW4831T-AS")
		product=IPC-HFW4830E
		aewcfg=IPC-HFW4830E
		;;
	"IPC-HDBW4231E-AS" | "IPC-HFW4231E-S" | "IPC-HFW4231B-BAS" | "IPC-HFW4231D-BAS" | "IPC-HDB4231C-AS" | "IPC-HDBW4231F-AS" | "IPC-HDW4231EM" | "IPC-HDW4231M" | "IPC-HFW4231S-S2" | "IPC-HDW4233C-S2" | "IPC-HDB4231C-M12" | "IPC-HDBW4231F-M12" | \
	"IPC-HDBW4233R" | "IPC-HDB4231G" | "IPC-HDP4231G" | "IPC-HDPW4238-WPT-SA" | "IPC-HDPW4233-PT-SA" | "IPC-HFW4231T-AS" )
		product=IPC-HF4231E
		case $sensor_id in
			74)
				aewcfg=IPC-HF5231E
				;;
			106)
				aewcfg=IPC-IMX307-REPLACE290
				;;
			118)
				aewcfg=IPC-IMX327-REPLACE290
				;;
			*)
				aewcfg=IPC-HF5231E
				;;
		esac
		;;
	"IPC-HFW4231E-S-S4" | "IPC-HDBW4231E-AS-S4" | "IPC-HDW4231EM-AS-S4" )
		product=IPC-HF4231E
		aewcfg=IPC-IMX307
		;;
	"IPC-HFW4233K-AS-WS")
		product=IPC-HFW4233K-AS-WS
		aewcfg=IPC-HF5231E
		;;
	"IPC-HUM7230-E1" | "IPC-HUM7233-E1")
		product=IPC-HF4231E
		aewcfg=IPC-HUM8230
		noLechange=1
		;;
	"IPC-HUM8230P-E1" | "IPC-HUM8231" | "IPC-HUM8231P-E1")
		product=IPC-HF4231E
		aewcfg=IPC-HUM8230
		;;
	"IPC-HUM7233-E2" | "IPC-HUM8231P-E2")
		product=IPC-HUM7233-E2
		aewcfg=IPC-HUM7233-E2
		noLechange=1
		;;
	"IPC-MW4231AP-E2" | "IPC-MW4231AP-E2-V2")
		product=IPC-MW4231AP-E2
		aewcfg=IPC-RM26
		noLechange=1
		;;
	"IPC-MW4231AP-E2")
		product=IPC-HUM7233-E2
		aewcfg=IPC-RM26
		noLechange=1
		;;
	"IPC-HDBW7233X-AS-E2-0280B" | "IPC-HDBW4231FP-E2-M")
		product=IPC-HDBW7233X-AS-E2
		aewcfg=IPC-HDBW7233X-AS-E2
		noLechange=1
		;;
	"IPC-HFW4231M" | "IPC-HFW4231M-AS" | "IPC-HDW4231C-S2")
		product=IPC-HF4231E
		aewcfg=IPC-HFW4231M
		;;
	"IPC-HDBW4431E-AS" | "IPC-HFW4431E-S" | "IPC-HFW4431B-BAS" | "IPC-HFW4431D-BAS" | "IPC-HDB4431C-AS" | "IPC-HDBW4431F-AS" | "IPC-HDW4431EM" | "IPC-HDW4431M" | "IPC-HFW4431S-S2" | "IPC-HDW4431C-S2" | "IPC-HDB4431C-M12" | "IPC-HDBW4431F-M12" | "IPC-HFW4431KM-S2" | \
	"IPC-HFW4431KM-AS-S2" | "IPC-HFW4431K-I6-S2" | "IPC-HFW4431K-AS-I6-S2" | "IPC-HDBW4431R-S2" | "IPC-HDB4431G" | "IPC-HDP4431G" | "IPC-HDPW4436-WPT-SA" | "IPC-HDPW4431-PT-SA" | "IPC-HFW4431T-AS" | "IPC-HFW4431E-S-S4" | "IPC-HDBW4431E-AS-S4" | "IPC-HDW4431EM-AS-S4")
		product=IPC-HF4431E
		aewcfg=IPC-HF5431E
		;;
	"IPC-EW4431-S" | "IPC-EW4431-SW" | "IPC-EW4431-ASW" | "IPC-EW5431-S" | "IPC-EW5431-SW" | "IPC-EW5431-ASW")
		product=IPC-EW4431
		aewcfg=IPC-EW4431
		;;
	"IPC-EW5531-AS")
		product=IPC-EW5531
		aewcfg=IPC-OS05A20-IR
		;;
	"IPC-HDBW5830R" | "IPC-HDW5830R-Z" | "IPC-HFW5830E-Z" |  "IPC-HFW5830E-ZH" |  "IPC-HDBW5830EP-Z-S2" |  "IPC-HDBW5830EP-ZH-S2" | "IPC-HDBW5830E-Z-S2" |  "IPC-HDBW5830E-ZH-S2" | "IPC-HDBW5830EP-Z-S2-2713" | "IPC-HDBW5830EP-ZH-S2-2713" |\
	"IPC-HDBW5830EP-Z-S3" | "IPC-HDBW5830EP-ZH-S3" | "IPC-HFW5830E-Z-S3" | "IPC-HFW5830E-ZH-S3" | "IPC-HDW5830RP-Z-S2" | "IPC-HDBW5831GP-Z-2712-S3")
		product=IPC-HDBW5830R
		aewcfg=IPC-HFW4830E
	;;
	"IPC-HFW5830E-ZH-0735" |"IPC-HDBW5830EP-Z-0735-S2" | "IPC-HDBW5830E-Z-0735-S2" |"IPC-HDBW5830E-ZH-0735-S2" |"IPC-HDBW5830EP-ZH-0735-S2"| "IPC-HFW5830E-Z-0735" | "IPC-HDBW5830EP-Z-0735-S3" | "IPC-HDBW5830EP-ZH-0735-S3" |\
	"IPC-HFW5830E-Z-0735-S3" | "IPC-HFW5830E-ZH-0735-S3" | "IPC-HDBW5831GP-Z-0735-S3")
		product=IPC-HDBW5830R
		aewcfg=IPC-HFW5830E-Z-0735
	;;	
	"IPC-HFW4530E-S" | "IPC-HDW4530EM" | "IPC-HDW4530C")
		product=IPC-HFW4530E
		aewcfg=IPC-HFW4530E
	;;
	"IPC-HDW2231RP-ZS" | "IPC-HDBW2231R-Z" | "IPC-HDBW2231R-VF" | "IPC-HFW2231R-VFS" | "IPC-HFW2231R-ZS" | "IPC-HDBW2231R-Z-2713" | "IPC-HDBW2231R-Z-2713" | "IPC-HFW2231R-ZS-2713" | "IPC-HDW2231RP-ZS-2713" | \
	"IPC-HFW2231T-ZS-2713" | "IPC-HFW2231T-ZAS-2713")
		product=IPC-HF2231R
		aewcfg=IPC-HF5231E
	;;
	"IPC-HDW2230RP-ZS" | "IPC-HDBW2230R-Z" | "IPC-HDBW2230R-VF" | "IPC-HFW2230R-VFS" | "IPC-HFW2230R-ZS" | "IPC-HDBW2230R-Z-2713" | "IPC-HDBW2230R-Z-2713" | \
	"IPC-HDBW2230R-Z-2713" | "IPC-HFW2230R-ZS-2713" | "IPC-HDW2230RP-ZS-2713" | "IPC-HFW2230T-ZS-2713" | "IPC-HFW2230T-ZAS-2713" )
		product=IPC-HF2231R
		aewcfg=IPC-HDW2230RP-ZS
	;;
	"IPC-HFW2235M-W-S" | "IPC-HFW2235M-W4G-AS" | "IPC-HFW2231MP-4G-AS" | "IPC-HFW2235M-W4G-S")
		product=IPC-HFW2235M-W4G-AS
		aewcfg=IPC-HDW2230RP-ZS
		;;
	"IPC-HDBW1230E" | "IPC-HDBW1230E-S"|"IPC-HDW1230S" | "IPC-HFW1230S" |"IPC-HFW1230SN" | "IPC-HDW1230SN")
		product=IPC-HF2231R
		aewcfg=IPC-TF26
	;;
	"IPC-HFW1431SN" | "IPC-HDW1431SN" | "IPC-HDW1431S" | "IPC-HFW1431S" | "IPC-HDBW1431E" | "IPC-HDBW1431E-S" | "IPC-HFW1431S-S2" | "IPC-HDPW1431FP-AS")
		product=IPC-HF2431R
		aewcfg=IPC-HF5431E
		;;
	"IPC-HDW2431RP-ZS" | "IPC-HDBW2431R-Z" | "IPC-HDBW2431R-VF" | "IPC-HFW2431R-VFS" | "IPC-HFW2431R-ZS" | "IPC-HDBW2431R-Z-2713" | "IPC-HDBW2431R-Z-2713" | \
	"IPC-HFW2431R-ZS-2713" | "IPC-HDW2431RP-ZS-2713" | "IPC-HFW2431T-ZS-2713" | "IPC-HFW2431T-ZAS-2713")
		product=IPC-HF2431R
		aewcfg=IPC-HF5431E
	;;
	"IPC-HDBW5631R-ZS-2713" | "IPC-HDBW5631R-ZAS-2713" | "IPC-HDBW5631RP-Z-2713" | "IPC-HFW5631E-Z-2713" | "IPC-HFW5631E-Z-2713" | "IPC-HFW5631E-ZH-2713" | "IPC-HFW5631E-Z-IRA-2713" | "IPC-HFW5631K-Z-I4-2713" | "IPC-HFW4631R-ZS-2713" | "IPC-HFW4631R-ZAS-2713" | "IPC-HDBW5631EP-Z-S2-2713" | \
	"IPC-HDBW5631EP-ZH-S2-2713" | "IPC-HDBW5631E-Z-2713" | "IPC-HDW5631RP-Z-S2-2713" | "IPC-HDBW5631R-ZAS" | "IPC-HDBW5631R-VFAS" | "IPC-HDBW5631R-ZS" | "IPC-HDBW5631R-VFS" | "IPC-HDBW5631RP-Z" | "IPC-HDBW5631EP-Z-S2" | "IPC-HDBW5631EP-ZH-S2" |  \
	"IPC-HDBW5631E-Z" | "IPC-HDW5631RP-Z-S2" | "IPC-HFW5631E-Z" | "IPC-HFW5631E-Z" | "IPC-HFW5631E-ZH" | "IPC-HFW5631E-Z-IRA" | "IPC-HFW5631K-Z-I4" | \
	"IPC-HF5631F" | "IPC-HFW4631R-VFS" | "IPC-HFW4631R-VFAS" | "IPC-HFW4631R-ZS" | "IPC-HFW4631R-ZAS" |  \
	"IPC-HFW5631E-Z-27135" | "IPC-HFW5631E-Z-X-27135" | "IPC-HDBW5631E-Z-27135" | "IPC-HDBW5631E-Z-X-27135" | "IPC-HFW5631E-Z-IRA-27135" | "IPC-HFW5631K-Z-I4-27135" | "IPC-HFW5631E-Z-IRA-X-27135" | "IPC-HFW5631K-Z-I4-X-27135" | \
	"IPC-HDB5631E-Z-27135" | "IPC-HDB5631E-Z-X-27135" | "IPC-HFW5631E-Z-IRA-27135-AC24" | "IPC-HFW5631E-Z-IRA-X-27135-24V" | "IPC-HFW5631E-Z-IRA-X1-27135" |\
	"IPC-HFW5631E-Z-27135-AC24V" | "IPC-HFW5631E-Z-X1-27135-AC24V" | "IPC-HFW5631E-Z-27135-S3" | "IPC-HFW5631E-ZH-27135-S3" |  \
	"IPC-HFW5631E-Z-IRA-27135-AC24V" | "IPC-HFW5631E-Z-27135-S3" | "IPC-HFW5631E-ZH-27135-S3" | "IPC-HFW5631K-Z-I4-27135-AC24V" | "IPC-HFW5631K-Z-I4-X-27135-AC24V" | "IPC-HDBW5631GP-Z-27135-S3")
		product=IPC-HF5631E
		is600w=1		
		aewcfg=IPC-HF5631E
	;;
  "IPC-HDBW5631EP-Z-0735-S2" | "IPC-HDBW5631EP-ZH-0735-S2" | "IPC-HDBW5631E-Z-0735" | "IPC-HFW5631E-Z-0735" | "IPC-HFW5631E-ZH-0735" | "IPC-HFW5631E-Z-IRA-0735" | "IPC-HFW5631K-Z-I4-0735" | "IPC-HDBW5631E-Z-X-0735" | "IPC-HFW5631E-Z-IRA-X-0735" | "IPC-HFW5631E-Z-X-0735" | "IPC-HFW5631K-Z-I4-X-0735" | "IPC-HDB5631E-Z-0735" | "IPC-HDB5631E-Z-X-0735" |\
  "IPC-HFW5631E-Z-IRA-0735-AC24V" | "IPC-HFW5631E-Z-0735-AC24V" | "IPC-HFW5631E-Z-X1-0735-AC24V" | "IPC-HFW5631E-Z-0735-S3" | "IPC-HFW5631E-ZH-0735-S3" | "IPC-HFW5631E-Z-0735-S3" | "IPC-HFW5631E-ZH-0735-S3" | "IPC-HFW5631E-Z-IRA-X-0735-24V" | "IPC-HFW5631K-Z-I4-0735-AC24V" | "IPC-HFW5631K-Z-I4-X-0735-AC24V" | "IPC-HDBW5631GP-Z-0735-S3")
		product=IPC-HF5631E
		is600w=1		
		aewcfg=IPC-HFW5631E-Z-0735
	;;
	"IPC-HDW4631EM" | "IPC-HDW5631C" | "IPC-HDBW5631R-AS" | "IPC-HDBW5631R-S" | "IPC-HDBW5631R-AS-B4" | "IPC-HFW4631EP-S" | "IPC-HFW4631MK" | "IPC-HFW4636K-I6" | "IPC-HFW5631MK-AS" | "IPC-HFW5631K-AS-I6" | "IPC-HFW5631MK-AS-B4" | "IPC-HDBW4631E-AS" | "IPC-HFW4631T-AS")
		product=IPC-HF4631E
		is600w=1		
		aewcfg=IPC-HF5631E
	;;
	"IPC-HFW4631K-AS-WS")
		product=IPC-HFW4631K-AS-WS
		is600w=1
		aewcfg=IPC-HF5631E
		;;
	"IPC-HFW4631F-VFS-27135" | "IPC-HFW4631F-VFAS-27135" | "IPC-HFW4631F-ZS-27135" | "IPC-HFW4631F-ZAS-27135" | "IPC-HFW4631F-VFAS-X-27135" | "IPC-HFW4631F-ZAS-X-27135" | \
	"IPC-HDBW4631R-VFS-27135" | "IPC-HDBW4631R-VFAS-27135" | "IPC-HDBW4631R-ZS-27135" | "IPC-HDBW4631R-ZAS-27135" | "IPC-HDBW4631R-VFAS-X-27135" | "IPC-HDBW4631R-ZAS-X-27135")
		product=IPC-HF4631E
		is600w=1		
		aewcfg=IPC-HF5631E
	;;
	"IPC-HDB8331E-0185B-S2" | "IPC-HDBW8331E-0185B" | "IPC-HDB5331E-0185B" | "IPC-HDBW5331E-0185B" | "IPC-HDB5331EP-0185B" ) 
	  product=IPC-HDB8331E
	  aewcfg=IPC-HDB8331E
	;;
	"IPC-HDB8331E-A2-0200B" | "IPC-HDBW8331E-A2-0200B")
	  product=IPC-HDB8331E-0200B
	  aewcfg=IPC-HDB8331E
	;;
	"IPC-HMW7335-A" | "IPC-HMW7335-AS" | "IPC-HMW7335-SA-0210B-SHDT")
	  product=IPC-HMW7335
	  aewcfg=IPC-HMW7335
          noLechange=1
	;;
	"IPC-MDW4230P-M12" | "IPC-MDW4330P-M12")
	  product=IPC-HMW7335
	  aewcfg=IPC-HMW7335
	;;
	"IPC-HDB7330R-AS")
      product=IPC-HDB7330
	  aewcfg=IPC-HMW7335
	  noLechange=1
      	;;
	"IPC-HFW1531S" | "IPC-HDBW1531E" | "IPC-HDBW1531E-S" | "IPC-HDW1531S" )
		product=IPC-HF2531E
		case $sensor_id in
			99)
				aewcfg=IPC-HF2531E
				;;
			124)
				aewcfg=IPC-OS05A20
				;;
			*)
				aewcfg=IPC-HF2531E
				;;
		esac
	;;
	"IPC-HDW2531RP-ZS-27135-XW" | "IPC-HDW2531RP-ZS-27135" | "IPC-HFW2531R-VFS-IRE6-27135" | "IPC-HFW2531R-ZS-IRE6-27135" | "IPC-HFW2531R-VFAS-IRE6-27135" | "IPC-HFW2531RP-ZAS-IRE6-27135" |  "IPC-HDBW2531R-VFS-27135" | "IPC-HDBW2531R-ZS-27135" | "IPC-HDBW2531R-VFAS-27135" | "IPC-HDBW2531R-ZAS-27135")
	  product=IPC-HF2531E
		case $sensor_id in
			99)
				aewcfg=IPC-HF2531E
				;;
			124)
				aewcfg=IPC-OS05A20
				;;
			*)
				aewcfg=IPC-HF2531E
				;;
		esac
	;;
	"IPC-TA26")
		product=IPC-TA26
		aewcfg=IPC-TF26
	;;
	"CE-TC5S" )
		product=CE-TC5S
		aewcfg=IPC-TF26
	;;
	"IPC-MBW7233-H" | "IPC-MBW7233-H-AS")
		product=IPC-HF4231E
		aewcfg=IPC-MBW4231
		isMBW200w=1
		noLechange=1
	;;
	"IPC-MBW4231-H" | "IPC-MBW4231-H-AS" | "IPC-MBW4231-H-M12")
		product=IPC-HF4231E
		aewcfg=IPC-MBW4231
		isMBW200w=1
	;;
	"IPC-MBW7431-H" | "IPC-MBW7431-H-AS")
		product=IPC-HF4431E
		aewcfg=IPC-MBW4431
		isMBW400w=1
		noLechange=1
		;;
	"IPC-MBW4431-H" | "IPC-MBW4431-H-AS" | "IPC-MBW4431-H-M12")
		product=IPC-HF4431E
		aewcfg=IPC-MBW4431
		isMBW400w=1
		;;
	"IPC-HUM7431-E1")
		product=IPC-HF4431E
		aewcfg=IPC-HUM8431
		noLechange=1
	;;
	"IPC-HUM8431P-E1")
		product=IPC-HF4431E
		aewcfg=IPC-HUM8431
	;;
	"IPC-EB5531P" | "IPC-EB5531" | "IPC-EB5531-M" | "IPC-EB5531-M12" | "IPC-EB5531-AS")
		product=IPC-EB5531P
		aewcfg=IPC-EB5531
		noLechange=1
	;;
	"IPC-HDW7243X" | "IPC-HDW8241X-3D")
		product=IPC-HDW7243X
		aewcfg=IPC-HDW7243X
	;;
	"IPC-HDW7341X-B-E2")
		product=IPC-HDW7341X-B-E2
		aewcfg=IPC-HDW7243X
	;;
	"IPC-HDBW4231F-MPC" | "IPC-HDB4231F-MPC" | "IPC-HDB4231F-M12PC")
		product=IPC-HDBW4231F-MPC
		aewcfg=IPC-HF5231E
	;;
	"IPC-HDBW4236-JTK")
		product=IPC-HDB4236-JTK
		aewcfg=IPC-HF5231E
		jtktype=LFW
	;;
	"IPC-HDB4236-JTK")
		product=IPC-HDB4236-JTK
		aewcfg=IPC-HF5231E
		jtktype=LF
	;;
	"IPC-RM26-4G" | "IPC-RM26-4G-V2")
		product=IPC-RM26-4G
		aewcfg=IPC-RM26
	;;
	"IPC-RM26" | "IPC-RM26-V2")
		product=IPC-RM26
		aewcfg=IPC-RM26
	;;
	"IPC-AW46W-5G")
		product=IPC-AW46W-5G
		aewcfg=IPC-HF5431E
	;;
	"IPC-HF5233E" | "IPC-HF5233E-E" | "IPC-HFW5233E-Z-27135" | "IPC-HFW5233K-Z-I2-27135" | "IPC-HFW5233E-Z-X1-27135" | "IPC-HFW5233K-Z-I2-X1-27135" | \
	"IPC-HDBW5233E-Z-27135" | "IPC-HDB5233E-Z-27135" | "IPC-HDBW5233E-Z-X1-27135" | "IPC-HDB5233E-Z-X1-27135")
		product=IPC-HF5231E
		aewcfg=IPC-IMX307
		;;
	"IPC-HFW5233K-Z-I4-X1-0735" | "IPC-HFW5233E-Z-IRA-X1-0560")
		product=IPC-HF5231E
		aewcfg=IPC-IMX307
		;;
	"IPC-HF5433E" | "IPC-HF5433E-E" | "IPC-HFW5433E-Z-27135" | "IPC-HFW5433K-Z-I2-27135" | "IPC-HFW5433E-Z-X1-27135" | "IPC-HFW5433K-Z-I2-X1-27135" | "IPC-HFW5438E-Z-27135-S2" | "IPC-HFW5438E-Z-X1-27135-S2" | \
	"IPC-HDBW5433E-Z-27135" | "IPC-HDB5433E-Z-27135" | "IPC-HDBW5433E-Z-X1-27135" | "IPC-HDB5433E-Z-X1-27135" | "IPC-HDBW5438E-Z-27135" | "IPC-HDB5438E-Z-27135-S2" | "IPC-HDBW5438E-Z-X1-27135-S2" | "IPC-HDB5438E-Z-X1-27135-S2")
		product=IPC-HF5431E
		case $sensor_id in
			99)
				aewcfg=IPC-HF2531E
				;;
			124)
				aewcfg=IPC-OS05A20
				;;
			*)
				aewcfg=IPC-HF2531E
				;;
		esac
		;;
	"IPC-HFW5433K-Z-I4-X1-0735" | "IPC-HFW5433E-Z-IRA-X1-0560")
		product=IPC-HF5431E
		case $sensor_id in
			99)
				aewcfg=IPC-HF2531E
				;;
			124)
				aewcfg=IPC-OS05A20
				;;
			*)
				aewcfg=IPC-HF2531E
				;;
		esac
		;;
	"IPC-HFW4239T-ASE-NI" | "IPC-HDBW4239R-ASE-NI")
		product=IPC-HF4231E
		aewcfg=IPC-IMX327-HFW4239
		;;
	"IPC-HFW5238E-Z-27135-S2" | "IPC-HFW5238E-Z-X1-27135-S2" | "IPC-HDBW5238E-Z-27135-S2" | "IPC-HDB5238E-Z-27135-S2" | "IPC-HDBW5238E-Z-X1-27135-S2" | "IPC-HDB5238E-Z-X1-27135-S2")
	    product=IPC-HF5231E
		aewcfg=IPC-IMX327
		;;
	"IPC-HFW1831C-PIR")
		product=IPC-HFW1831C-PIR
		aewcfg=IPC-HFW4830E
		;;
	"IPC-HFW1231S" | "IPC-HDW1231S" | "IPC-HDBW1231E" | "IPC-HDBW1231E-S" | "IPC-HDBW3231E-AS")
		product=IPC-HF2231R
		aewcfg=IPC-IMX307
		;;
	"IPC-HDPW1231FP-AS")
		product=IPC-HF2231R
		aewcfg=IPC-IMX307-HDPW1231
		;;
esac

case "$product_name" in
	"IPC-HDW2231RP-ZS" | "IPC-HDW2231RP-ZS-2713" | "IPC-HDBW2231R-Z" | "IPC-HDBW2231R-Z-2713" | "IPC-HFW2231R-ZS" | "IPC-HFW2231R-ZS-2713" | "IPC-HFW2231T-ZS-2713" | "IPC-HFW2231T-ZAS-2713" | "IPC-HFW2231R-VFS" | "IPC-HDBW2231R-VF")
			case $sensor_id in
			74)
				aewcfg=IPC-HF5231E
				;;
			106)
				aewcfg=IPC-IMX307
				;;
			*)
				aewcfg=IPC-HF5231E
				;;
		esac
esac

if [ "$fvideo_chip" = "34" ];then
	if  [ "$dspChip" = "24" ];then
		product=IPC-HX4XX_Limit
	fi
fi

#国内2系需要去掉部分智能功能
if [ "$hwid_value" = "IPC-HDBW4220E:01:02:05:33:18:00:01:00:00:00:00:258:00:00:00:00:00:01:00:00:100" ];then
	if [ -f /usr/data/Strings/SimpChinese.txt ];then
		product=IPC-HX2220_Chn
	fi
fi

echo product=$product

if [ $cap_3g -eq 1 ];then
	echo host > /proc/ambarella/usbphy0 
	insmod /usr/lib/modules/usbserial.ko
	insmod /usr/lib/modules/usb_wwan.ko
	insmod /usr/lib/modules/option.ko
	insmod /usr/lib/modules/usbnet.ko
	insmod /usr/lib/modules/cdc_ether.ko
	net3g&
fi

if [ "$product" != "" ];then
	if [ "$mp_autotest_flag" != "1" ];then
		cp -f /var/tmp/product/$product/* /var/tmp/pd/
	else
		cp -f /mnt/pd/product/$product/*  /var/tmp/pd/
	fi
fi

if [ $cap_wifi -ne 0 ];then
	lineNum=`sed -n "/T2UServer/,/Enable/"= /var/tmp/pd/CustomConfig | sed -n "$"p`
	if [ "$lineNum" != "" ];then
		sed -i $lineNum"s/false/true/g" /var/tmp/pd/CustomConfig
	fi
fi

if [ $noLechange -ne 0 ];then
	sed -i "s/\"VSPs\" : \[ \"LechangePro\" \]/\"VSPs\" : \[ \"None\" \]/" /var/tmp/pd/ProductDefinition

	lineNum=`sed -n "/T2UServer/,/Enable/"= /var/tmp/pd/CustomConfig | sed -n "$"p`
	if [ "$lineNum" != "" ];then
		sed -i $lineNum"s/true/false/g" /var/tmp/pd/CustomConfig
	fi
fi
if [ "$audioin"  = "0" ];then
	sed -i "s/\"VolumeDetect\" : true,/\"VolumeDetect\" : false,/"  /var/tmp/pd/ProductDefinition
	sed -i "s/\"AnomalyDetect\" : true,/\"AnomalyDetect\" : false,/"    /var/tmp/pd/ProductDefinition
	sed -i "s/\"MutationDetect\" : true,/\"MutationDetect\" : false,/"   /var/tmp/pd/ProductDefinition
	sed -i "s/\"AudioEnable\" : true,/\"AudioEnable\" : false,/"   /var/tmp/pd/CustomConfig
fi

if [ "$product_name" = "IPC-HFW4239T-ASE-NI" ] || [ "$product_name" = "IPC-HDBW4239R-ASE-NI" ];then
sed -i "s/\"Mode\" : \"Brightness\"/\"Mode\" : \"Color\"/" /var/tmp/pd/CustomConfig
fi

if [ "$product_name" = "IPC-HFW4631F-VFS-27135" ] || [ "$product_name" = "IPC-HFW4631F-ZS-27135" ];then
	sed -i "s/\"AudioEnable\" : true,/\"AudioEnable\" : false,/"   /var/tmp/pd/CustomConfig
fi
#600W设备国内需要实时分辨率,中文1\2\4系列辅码流要求码流降低到512K
if [ -f /usr/data/Strings/SimpChinese.txt ];then
	if [ $is600w -eq 1 ];then
	sed -i "s/\"3072x2048\"/\"2592x1944\"/" /var/tmp/pd/CustomConfig
	fi
	
	if [ "$product" = "IPC-HF1231R" ] || [ "$product" = "IPC-HF2231R" ] || [ "$product" = "IPC-HF1431R" ] || [ "$product" = "IPC-HF2431R" ] || [ "$product" = "IPC-HF1531E" ]|| [ "$product" = "IPC-HF2531E" ] || [ "$product" = "IPC-HF4231E" ] || [ "$product" = "IPC-HF4431E" ] || [ "$product" = "IPC-HF4631E" ] || [ "$product" = "IPC-HFW4530E" ] || [ "$product" = "IPC-HFW4830E" ];then
	sed -i "s/\"BitRate\" : 1024,/\"BitRate\" : 512,/" /var/tmp/pd/CustomConfig
	fi
fi

#列车400W设备默认码流要求8M，避免运动中出现马赛克
if [ $isMBW400w -eq 1 ];then
	sed -i "s/\"BitRate\" : 4096,/\"BitRate\" : 8192,/" /var/tmp/pd/CustomConfig		
fi	

if [ $isMBW200w -eq 1 ];then
	sed -i "s/\"BitRate\" : 4096,/\"BitRate\" : 6144,/" /var/tmp/pd/CustomConfig
fi
if [ "$jtktype" != "0" ];then
	sed -i "s/\"RailwayDeviceType\" : \"LFW\"/\"RailwayDeviceType\" : \"$jtktype\"/" /var/tmp/pd/ProductDefinition
fi
#简单云台设备添加简单云台的能力
if [ $isSimplifiedPtz -eq 1 ];then
	sed -i -e '/\"MotionDetectWindow\" : 4,/a\\"IsSimplifiedPtz\" : true,' /var/tmp/pd/ProductDefinition
	sed -i -e '/\"MotionDetectWindow\" : 4,/a\\"PtzProtocolList\" : [\"DH-SD1\"],' /var/tmp/pd/ProductDefinition
	sed -i "s/\"IsProtectCover\" : true/\"IsProtectCover\" : false/" /var/tmp/pd/ProductDefinition
	sed -i -e 's/\"Action\" : \[ \"Tour\", \"Pattern\", \"Preset\", \"Scan\"/\"Action\" : \[ \"Tour\", \"Preset\"/' /var/tmp/pd/ProductDefinition
	sed -i -e 's/\"Action\" : \[ \"Tour\", \"Pattern\", \"Preset\", \"AutoScan\"/\"Action\" : \[ \"Tour\", \"Preset\"/' /var/tmp/pd/ProductDefinition
	sed -i "s/\"ProtocolName\" : \"PELCOD\"/\"ProtocolName\" : \"DH-SD1\"/" /var/tmp/pd/CustomConfig
fi
#创建/var/tmp/3A目录
mkdir -p /var/tmp/3A

if [ "$aewcfg" != "" ];then
#现在所有的CC_08_3D.bin公用一个，减少flash占用
	!(test -e "/var/tmp/2Acfg/$aewcfg/CC_08_3D.bin") && cp -f /var/tmp/2Acfg/IPC-Share/CC_08_3D.bin /var/tmp/2Acfg/$aewcfg/
	!(test -e "/var/tmp/2Acfg/$aewcfg/WDR_CC_01_3D.bin") && cp -f /var/tmp/2Acfg/IPC-Share/WDR_CC_01_3D.bin /var/tmp/2Acfg/$aewcfg/
	cp -rf /var/tmp/2Acfg/$aewcfg/* /var/tmp/3A/

fi
cp -f /var/tmp/2Acfg/reg.bin /var/tmp/3A/
(test -e "/mnt/mtd/3A/aew_para.zip") && unzip /mnt/mtd/3A/aew_para.zip -d /var/tmp/3A > /dev/null

#将打包中的aew_para赋值到内存中，以便进行版本比较，如果比flash的要新，则更换掉flash中的版本
cp -rf /usr/data/aewParam/$aewcfg/* /var/tmp/
(test -e "/var/tmp/aew_para.zip") && unzip /var/tmp/aew_para.zip -d /var/tmp > /dev/null
(test -e "/var/tmp/3A/pre_aew_work") && /var/tmp/3A/pre_aew_work
#根据不同的设备类型拷贝聚焦库配置
#默认为手动镜头,其配置文件统一放入IPC-HF5100中
afcfg=manual
echo "Default manual len in manual"
case "$product_name" in     
        #电动镜头福光2.8-12mm,其配置文件统一放入fuguang0028-0120
        "IPC-HDW2220R-Z"|"IPC-HFW5220E-Z"|"IPC-HDBW5221E-Z"|"IPC-HDBW5221E-ZH"|"IPC-HDB5221E-Z"|"IPC-HDBW5220E-Z"|"IPC-HDBW5221EP-Z"|"IPC-HDBW5221EP-ZH"|"IPC-HDBW5220EP-Z"|"IPC-HDBW5220EP-ZH"|"IPC-HFW5220D-Z" | "IPC-HFW5220E-ZH" | "IPC-HDBW5221E-Z-A2")
        	if [ "$lens_type" = "1" ];then
			afcfg=fuguang_nv_0028-0120
		        cap_af="AF"
		        echo "abf len in fuguang_nv_0028-0120"
		elif [ "$lens_type" = "0" ];then
			afcfg=fuguang0028-0120
			cap_af="AF"
			echo "FuGuang 2.8-12mm len in fuguang0028-0120"	
		elif [ "$lens_type" = "2" ];then
			afcfg=fuguang_nv_0035-0120
			cap_af="AF"
			echo "FuGuang 3.5-12mm len in fuguang_nv_0035-0120"	
		elif [ "$lens_type" = "3" ];then
			afcfg=fuguang_nv_0070-0220
			cap_af="AF"
			echo "FuGuang 7.0-22mm len in fuguang_nv_0070-0220"	
		fi
        	;;
	#新的yutong二代镜头，其配置文件统一放入yutong0027-0120-6
        "IPC-HFW5121D-Z" | "IPC-HDW2120R-Z"|"IPC-HFW5121E-Z"|"IPC-HDBW5121E-Z"|"IPC-HDBW5121E-ZH"|"IPC-HDB5121E-Z"|"IPC-HDBW5120E-Z"|"IPC-HDBW5121EP-Z"|"IPC-HDBW5121EP-ZH"|"IPC-HDBW5120EP-Z" | "IPC-HFW5120D-Z" | "IPC-HFW5120E-Z" | "IPC-HFW5121E-ZH" | "IPC-HDW4120R-Z" | "IPC-HFW2120R-ZS" | "IPC-HDBW2120R-ZS" | \
		"IPC-HFW4120R-ZAS" | "IPC-HFW4120R-Z" | "IPC-HDBW5121E-Z-A2")
		if [ "$lens_type" = "0" ];then
		       afcfg=yutong0027-0120-6
		       cap_af="AF"
		       echo "YuTong 2.7-12mm len in yutong0027-0120-6"
		elif [ "$lens_type" = "3" ];then
			   afcfg=fuguang_nv_0070-0220
			   cap_af="AF"
			   echo "FuGuang 7.0-22mm len in fuguang_nv_0070-0220"	
	        fi
		;;
        "IPC-HF5120E" | "IPC-HF5121E" | "IPC-HF5221E" | "IPC-HF5421E" | "IPC-HF5220E" | "IPC-HF5121E-A2" | "IPC-HF5221E-A2" | "IPC-HF5421E-A2"|"IPC-HF5231E"|"IPC-HF5431E" | "IPC-HF5433E" | "IPC-HF5433E-E" | "IPC-HF5233E" | "IPC-HF5233E-E")
		afcfg=ABF
		cap_af="AF"
		echo "abf len in ABF"
		;;
		
		"IPC-HF5631F")
		afcfg=ABF_B5
		cap_af="AF"
		echo "abf len in ABF_B5"
		;;
	#fuguang3.5~12镜头设备
        "IPC-HFW5221D-Z"|"IPC-HFW5221E-Z" | "IPC-HFW5221E-ZH")
                if [ "$lens_type" = "2" ];then
			afcfg=fuguang_nv_0035-0120
		        cap_af="AF"
		        echo "abf len in fuguang_nv_0035-0120"
	        elif [ "$lens_type" = "0" ];then
			   afcfg=fuguang0035-0120
			   cap_af="AF"
			   echo "FuGuang 2.8-12mm len in fuguang_nv_0035-0120"	
		elif [ "$lens_type" = "3" ];then
			   afcfg=fuguang_nv_0070-0220
			   cap_af="AF"
			   echo "FuGuang 7.0-22mm len in fuguang_nv_0070-0220"	
	        fi
		;;
     	#fuguang_NV2.8~12镜头设备
        "IPC-HDBW5421EP-Z"|"IPC-HDBW5421EP-ZH"|"IPC-HFW5421D-Z"|"IPC-HDBW5421E-Z"|"IPC-HDBW5421E-ZH"|"IPC-HDB5421E-Z"|"IPC-HFW5421E-Z" | "IPC-HFW5421E-ZH"|"IPC-HDW2320R-Z" | "IPC-HDW2421R-Z" | "IPC-HFW2320R-ZS" | "IPC-HDBW2320R-ZS" | \
		"IPC-HFW4220R-ZAS" | "IPC-HFW4220R-Z" | "IPC-HFW2220R-ZS" | "IPC-HDBW2220R-ZS"  | "IPC-HDW4220R-Z" | "IPC-HDBW2320R-ZAS" | "IPC-HDBW5421E-Z-A2" | "IPC-HFW2320R-Z" |"IPC-HDBW5431R-Z" )
		afcfg=fuguang_nv_0028-0120
		cap_af="AF"
		echo "abf len in fuguang_nv_0028-0120"
		;;
	#UNION_STEP_0047_0470镜头设备
        "IPC-HFW5121E-CA-IRA"|"IPC-HFW5221E-CA-IRA"|"IPC-HFW5221D-CA"|"IPC-HFW5421E-CA-IRA")
		afcfg=UNION_STEP_0047_0470
		cap_af="AF"
		echo "UNION len in UNION_STEP_0047_0470"
		;;
		
	#fuguang_nv_0035-0120
		"IPC-HFW8321EN-Z" | "IPC-HFW8221EN-Z" | "IPC-HDBW8321EN-Z" | "IPC-HDBW8221EN-Z" |"IPC-HDBW5231R-Z")
			afcfg=fuguang_nv_0035-0120
		    cap_af="AF"
		    echo "abf len in fuguang_nv_0035-0120"
		;;
	#fuguang_IR_0028-0120	
	   "IPC-HDW5231R-Z"|"IPC-HFW5231E-Z"|"IPC-HDBW5231EP-Z-S2"|"IPC-HDBW5231E-Z-S2" | "IPC-HDBW5231EP-ZH-S2" | "IPC-HFW5231E-ZH")
	        if [ "$lens_type" = "1" ];then
			afcfg=fuguang_ir_0028-0120
		        cap_af="AF"
		        echo "abf len in fuguang_ir_0028-0120"
	        elif [ "$lens_type" = "0" ];then
			   afcfg=fuguang_nv_0035-0120
			   cap_af="AF"
			   echo "FuGuang 2.8-12mm len in fuguang_nv_0035-0120"	
			fi
		;;
		
	#fuguang_IR_0027-0120	
	   "IPC-HDW5431R-Z"|"IPC-HFW5431E-Z"|"IPC-HDBW5431EP-Z-S2"|"IPC-HDBW5431E-Z-S2"|"IPC-HDBW5431EP-ZH-S2"|"IPC-HFW5431E-ZH")
	       if [ "$lens_type" = "2" ];then
			afcfg=fuguang_ir_0027-0120
		        cap_af="AF"
		        echo "abf len in fuguang_ir_0027-0120"
	        elif [ "$lens_type" = "0" ];then
			   afcfg=fuguang_nv_0028-0120
			   cap_af="AF"
			   echo "FuGuang 2.8-12mm len in fuguang_nv_0028-0120"	
			elif [ "$lens_type" = "1" ];then
			   afcfg=fuguang_ir_0028-0120
			   cap_af="AF"
			   echo "FuGuang 2.8-12mm len in fuguang_ir_0028-0120"	
			fi
		;;
	#fuguang_IR_0033-0120	
	 "IPC-HDBW5830EP-Z-S2"|"IPC-HDBW5830E-Z-S2"|"IPC-HDBW5830EP-ZH-S2"|"IPC-HDBW5830E-ZH-S2"|"IPC-HDBW5830R"|"IPC-HFW5830E-ZH"|"IPC-HFW5830E-Z"|"IPC-HDW5830R-Z"|\
	 "IPC-HDBW5830EP-Z-S3" | "IPC-HDBW5830EP-ZH-S3" | "IPC-HFW5830E-Z-S3" | "IPC-HFW5830E-ZH-S3" | "IPC-HDW5830RP-Z-S2" | "IPC-HDBW5831GP-Z-2712-S3")
	     afcfg=fuguang_ir_0033-0120
		        cap_af="AF"
		        echo "abf len in fuguang_ir_0033-0120"
	 ;;
	 #yasico_0007-0035	
	 "IPC-HDBW5231EP-Z-0735-S2"|"IPC-HDBW5431EP-Z-0735-S2"|"IPC-HDBW5231E-Z-0735-S2"|"IPC-HDBW5431E-Z-0735-S2"|"IPC-HDBW5830EP-Z-0735-S2"|"IPC-HDBW5830EP-ZH-0735-S2"|\
	 "IPC-HDBW5830E-Z-0735-S2"|"IPC-HDBW5830E-ZH-0735-S2"|"IPC-HFW5231E-Z-0735"|"IPC-HFW5431E-Z-0735"|"IPC-HFW5830E-Z-0735"|"IPC-HFW5830E-ZH-0735" | "IPC-HDBW5631EP-Z-0735-S2"|\
	 "IPC-HDBW5631EP-ZH-0735-S2" | "IPC-HDBW5631E-Z-0735" | "IPC-HFW5631E-Z-0735" | "IPC-HFW5631E-ZH-0735" | "IPC-HFW5631E-Z-IRA-0735" |\
	 "IPC-HFW5631K-Z-I4-0735" | "IPC-HDBW5631E-Z-X-0735" | "IPC-HFW5631E-Z-IRA-X-0735" | "IPC-HFW5631E-Z-X-0735" | "IPC-HFW5631K-Z-I4-X-0735" |\
	 "IPC-HDBW5231EP-ZH-0735-S2" | "IPC-HDBW5431EP-ZH-0735-S2" | "IPC-HFW5231EP-ZH-0735-S2" | "IPC-HFW5431EP-ZH-0735-S2" | "IPC-HDB5631E-Z-0735" | "IPC-HDB5631E-Z-X-0735" |\
	 "IPC-HFW5631E-Z-IRA-0735-AC24V" | "IPC-HFW5631E-Z-0735-AC24V" | "IPC-HFW5631E-Z-X1-0735-AC24V" | "IPC-HFW5631E-Z-0735-S3" | "IPC-HFW5631E-ZH-0735-S3" |\
	 "IPC-HDBW5231EP-ZH-0735-S3" | "IPC-HDBW5231EP-Z-0735-S3" | "IPC-HDBW5431EP-ZH-0735-S3" | "IPC-HDBW5431EP-Z-0735-S3" | "IPC-HDBW5830EP-Z-0735-S3" | "IPC-HDBW5830EP-ZH-0735-S3" |\
	 "IPC-HFW5231E-Z-0735-S3" | "IPC-HFW5431E-Z-0735-S3" | "IPC-HFW5830E-Z-0735-S3" | "IPC-HFW5231E-ZH-0735-S3" | "IPC-HFW5431E-ZH-0735-S3" | "IPC-HFW5830E-ZH-0735-S3" |\
	 "IPC-HFW5631E-Z-0735-S3" | "IPC-HFW5631E-ZH-0735-S3" | "IPC-HFW5631E-Z-IRA-X-0735-24V" | "IPC-HDBW5831GP-Z-0735-S3" | "IPC-HDBW5631GP-Z-0735-S3" | "IPC-HDBW5431GP-Z-0735-S3" |\
	 "IPC-HDBW5231GP-Z-0735-S3" | "IPC-HFW5631K-Z-I4-0735-AC24V" | "IPC-HFW5631K-Z-I4-X-0735-AC24V" | "IPC-HFW5433K-Z-I4-X1-0735" | "IPC-HFW5233K-Z-I4-X1-0735")
	     afcfg=yasico_0007-0035
		        cap_af="AF"
		        echo "step len in yasico_0007-0035"
	 ;;
	#fuguang_ir_0027-0120	
	 "IPC-HDW2431RP-ZS"|"IPC-HDBW2431R-Z"|"IPC-HFW2431R-ZS"|"IPC-HFW2230R-ZS"|"IPC-HDBW2230R-Z"|"IPC-HDW2230RP-ZS")
	     afcfg=fuguang_ir_0027-0120
		        cap_af="AF"
		        echo "abf len in fuguang_ir_0027-0120"
	 ;;
	#fuguang_ir_0028-0120
	 "IPC-HDW2231RP-ZS"|"IPC-HDBW2231R-Z"|"IPC-HFW2231R-ZS")
	     afcfg=fuguang_ir_0028-0120
		        cap_af="AF"
		        echo "FuGuang 2.8-12mm len in fuguang_ir_0028-0120"
	 ;;
	#UNION_STEP_0053_0640
      "IPC-HFW5231E-Z12-S2" | "IPC-HFW5231E-Z-0560-S3" | "IPC-HFW5433E-Z-IRA-X1-0560" | "IPC-HFW5233E-Z-IRA-X1-0560")
		afcfg=UNION_STEP_0053_0640
		cap_af="AF"
		echo "UNION len in UNION_STEP_0053_0640"
		;;
	#yutong_0027_0111
	"IPC-HDBW2231R-Z-2713" | "IPC-HDBW2431R-Z-2713" | "IPC-HDBW2230R-Z-2713" | "IPC-HDBW2231R-Z-2713" | "IPC-HDBW2431R-Z-2713" | "IPC-HDBW2230R-Z-2713" | "IPC-HFW2230R-ZS-2713" |\
	"IPC-HFW2231R-ZS-2713" | "IPC-HFW2431R-ZS-2713" | "IPC-HDW2231RP-ZS-2713" | "IPC-HDW2230RP-ZS-2713" | "IPC-HDW2431RP-ZS-2713" | "IPC-HFW4631F-ZS-27135" | "IPC-HFW4631F-ZAS-27135" |\
	"IPC-HFW4631F-ZAS-X-27135" | "IPC-HDBW4631R-ZS-27135" | "IPC-HDBW4631R-ZAS-27135" | "IPC-HDBW4631R-ZAS-X-27135" |\
	"IPC-HDW2531RP-ZS-27135-XW" | "IPC-HDW2531RP-ZS-27135" | "IPC-HFW2531R-ZS-IRE6-27135" | "IPC-HFW2531RP-ZAS-IRE6-27135" | "IPC-HDBW2531R-ZS-27135" | "IPC-HDBW2531R-ZAS-27135" |\
	"IPC-HFW2230T-ZS-2713" | "IPC-HFW2231T-ZS-2713" | "IPC-HFW2431T-ZS-2713" | "IPC-HFW2230T-ZAS-2713" | "IPC-HFW2231T-ZAS-2713" | "IPC-HFW2431T-ZAS-2713")
	    afcfg=yutong_0032_0111
		cap_af="AF"
		echo "yutong len in yutong_0032_0111"
		;;
	#yutong_0032_0099
	"IPC-HFW5631E-Z" | "IPC-HFW5631E-ZH" | "IPC-HFW5631E-Z-IRA" | "IPC-HFW5631K-Z-I4" | "IPC-HDBW5631EP-Z-S2" | "IPC-HDBW5631E-Z" | "IPC-HDBW5631EP-ZH-S2" | "IPC-HDW5631RP-Z-S2" | "IPC-HDBW5631RP-Z")
		afcfg=yutong_0032_0099
		cap_af="AF"
		echo "yutong len in yutong_0032_0099"
		;;
	#yutong_0032_0104
	"IPC-HDBW5631E-Z-27135" | "IPC-HDBW5631E-Z-X-27135" | "IPC-HFW5631E-Z-27135" | "IPC-HFW5631E-Z-X-27135" | "IPC-HFW5631E-Z-IRA-27135" | "IPC-HFW5631E-Z-IRA-X-27135" | "IPC-HFW5631K-Z-I4-27135" |\
	"IPC-HFW5631K-Z-I4-X-27135" | "IPC-HDW5231R-Z-2713" | "IPC-HDW5431R-Z-2713" | "IPC-HFW5231E-Z-2713" | "IPC-HFW5431E-Z-2713" | "IPC-HFW5231E-ZH-2713" | "IPC-HFW5431E-ZH-2713" | "IPC-HFW5631E-Z-2713" |\
	"IPC-HFW5631E-ZH-2713" | "IPC-HFW5631E-Z-IRA-2713" | "IPC-HFW5631K-Z-I4-2713" | "IPC-HDBW5231EP-Z-S2-2713" | "IPC-HDBW5231EP-ZH-S2-2713" | "IPC-HDBW5431EP-Z-S2-2713" | "IPC-HDBW5431EP-ZH-S2-2713" |\
	"IPC-HDBW5830EP-Z-S2-2713" | "IPC-HDBW5830EP-ZH-S2-2713" | "IPC-HDBW5631EP-Z-S2-2713" | "IPC-HDBW5631EP-ZH-S2-2713" | "IPC-HDBW5631E-Z-2713" | "IPC-HDW5631RP-Z-S2-2713" | "IPC-HDB5631E-Z-27135" | "IPC-HDB5631E-Z-X-27135" |\
	"IPC-HFW5631E-Z-IRA-27135-AC24" | "IPC-HFW5631E-Z-IRA-X-27135-24V" | "IPC-HFW5631E-Z-IRA-X1-27135" | "IPC-HFW5631E-Z-27135-AC24V" | "IPC-HFW5631E-Z-X1-27135-AC24V" | "IPC-HFW5631E-Z-27135-S3" | "IPC-HFW5631E-ZH-27135-S3" |\
	"IPC-HDBW5231RP-Z-27135-S3" | "IPC-HDBW5431RP-Z-27135-S3" | "IPC-HDBW5631RP-Z-2713" | "IPC-HFW5631E-Z-IRA-27135-AC24V" | "IPC-HFW5631E-Z-27135-S3" | "IPC-HFW5631E-ZH-27135-S3"| "IPC-HDBW5631GP-Z-27135-S3" |\
	"IPC-HDBW5431GP-Z-27135-S3" | "IPC-HDBW5231GP-Z-27135-S3" | "IPC-HFW5631K-Z-I4-27135-AC24V" | "IPC-HFW5631K-Z-I4-X-27135-AC24V"| "IPC-HFW5233E-Z-27135" | "IPC-HFW5233K-Z-I2-27135" | "IPC-HFW5433E-Z-27135" | "IPC-HFW5433K-Z-I2-27135" |\
	"IPC-HFW5233E-Z-X1-27135" | "IPC-HFW5233K-Z-I2-X1-27135" | "IPC-HFW5433E-Z-X1-27135" | "IPC-HFW5433K-Z-I2-X1-27135" | "IPC-HDBW5233E-Z-27135" | "IPC-HDB5233E-Z-27135" | "IPC-HDBW5433E-Z-27135" | "IPC-HDB5433E-Z-27135" |\
	"IPC-HDBW5233E-Z-X1-27135" | "IPC-HDB5233E-Z-X1-27135" | "IPC-HDBW5433E-Z-X1-27135" | "IPC-HDB5433E-Z-X1-27135" | "IPC-HDBW5231EP-ZE-HDMI-27135")
		afcfg=yutong_0032_0104
		cap_af="AF"
		echo "yutong len in yutong_0032_0104"
		;;
		
	#yutong_0027_0135
	"IPC-HFW4431EP-Z-S4" | "IPC-HDBW4431E-Z-S4" | "IPC-HDW4431T-Z-S4" |\
	"IPC-HFW4231EP-Z-S4" | "IPC-HDBW4231E-Z-S4" | "IPC-HDW4231T-Z-S4")
		afcfg=yutong_IR_0027_0135
		cap_af="AF"
		echo "yutong len in yutong_0027_0135"
		;;
		
		
	#yutong_0032-0090
	    "IPC-HDBW5238E-Z-27135-S2" | "IPC-HFW5438E-Z-X1-27135-S2" | "IPC-HDBW5438E-Z-X1-27135-S2" | "IPC-HFW5438E-Z-27135-S2" | "IPC-HFW5238E-Z-X1-27135-S2" | "IPC-HDBW5238E-Z-27135-S2" | "IPC-HDB5238E-Z-27135-S2" | "IPC-HDBW5438E-Z-27135" | "IPC-HDB5438E-Z-27135-S2" | "IPC-HDBW5238E-Z-X1-27135-S2" | "IPC-HDB5238E-Z-X1-27135-S2" | "IPC-HDBW5438E-Z-X1-27135-S2" | "IPC-HDB5438E-Z-X1-27135-S2" | "IPC-HFW5238E-Z-27135-S2")
		afcfg=yutong_0032_0090
		cap_af="AF"
		echo "yutong len in yutong_0032_0090"
		;;
	
	#manual镜头设备
	    "IPC-HDP5121E"|"IPC-HDP5221E"|"IPC-HDP5421E"|"IPC-HDPW5121E"|"IPC-HDPW5221E"|"IPC-HDPW5421E"|"IPC-HFW2120R-VFS"|"IPC-HFW2220R-VFS"|"IPC-HFW2320R-VFS" | "IPC-HFW2421R-VFS" |\
		"IPC-HFW4120R-VFAS" | "IPC-HFW4120R-VF" | "IPC-HFW4220R-VFAS" | "IPC-HFW4220R-VF" | "IPC-HDBW4120R-VFAS" |\
		"IPC-HFW2231R-VFS" | "IPC-HDBW2231R-VF" | "IPC-HFW2431R-VFS" | "IPC-HDBW2431R-VF" | "IPC-HDBW2230R-VF" | "IPC-HFW2230R-VFS" |\
		"IPC-HFW4631F-VFS-27135" | "IPC-HFW4631F-VFAS-27135" | "IPC-HFW4631F-VFAS-X-27135" | "IPC-HDBW4631R-VFAS-27135" | "IPC-HDBW4631R-VFAS-X-27135" |\
		"IPC-HDBW4631R-VFS-27135" | "IPC-HFW2531R-VFS-IRE6-27135" | "IPC-HFW2531R-VFAS-IRE6-27135" | "IPC-HDBW2531R-VFS-27135" | "IPC-HDBW2531R-VFAS-27135")
		afcfg=manual
		cap_af="AF"
		echo "manual len in manual"
		;;
		
        #带云台,不会启动AF,不需要配置文件
		"IPC-HD4200-PT" | "IPC-HD4100-PT")
        	afcfg=
        	echo "Not support AF"
        	;;
esac
echo    $afcfg
echo    $product_name
if [ "$afcfg" != "" ];then
	cp -f /var/tmp/2Acfg/$afcfg/* /var/tmp/
fi

#复制云台相关配置文件
if [ "$ptzcfg" != "" ];then
	echo ptzcfg=$ptzcfg
	cp -f /var/tmp/ptzcfg/$ptzcfg.bin /var/tmp/ptz_cfg.bin
fi

if [ ! -f /mnt/mtd/Config/PresetFile ];then
    if [ ! -f /mnt/mtd/Config/PresetFileBackUp ];then
        if [ "$ptzPreset" != "" ];then
            echo ptzPreset=$ptzPreset
            cp -f /var/tmp/ptzcfg/$ptzPreset.bin /mnt/mtd/Config/PresetFile
        fi
    fi
fi
if [ "$ptzcal" != "" ];then
	echo ptzcal=$ptzcal
	cp -f /var/tmp/ptzcfg/$ptzcal.bin /var/tmp/ptz_cal.bin
fi

if [ ! -f /mnt/mtd/Config/osd.bmp ];then
	cp  -f /mnt/web/osd.bmp /mnt/mtd/Config/
	cp  -f /var/tmp/osd.bmp /mnt/mtd/Config/
fi

#网约车IPC型号存在两份2A配置，会导致config分区不够用，做转移
cap_db2A=0;
case "$product_name" in
        "IPC-MW4231AP-E2" | "IPC-MW4231AP-E2-V2")
        	cap_db2A=1
        	;;
esac
if [ "$cap_db2A" = "1" ];then
	mkdir -p /mnt/backup/3A/1
	rm /mnt/mtd/3A/1 -rf
	ln -s /mnt/backup/3A/1 /mnt/mtd/3A/1
fi

#删除临时目录
rm -rf /var/tmp/product
rm -rf /var/tmp/2Acfg
rm -rf /var/tmp/ptzcfg

#删除无用的3A文件
rm -f /mnt/mtd/3A/*3D.bin
rm -f /mnt/mtd/3A/af*.bin
#exit 0
#configuration

cap_ex2=""
grep '\"MaxExtraStream\" : 2' /usr/data/ProductInfo > /dev/null
if [ "$?" = "0" ];then
cap_ex2="EX2"
fi

#是否为智能标记位，0表示非智能，1表示智能,由\Specialities\Intelligent\IVS下的build.cfg进行修改
Is_IVS=1
cap_dsp="DSP"
if [ $Is_IVS -eq 0 ];then
	cap_dsp=""
fi
echo cap_dsp = $cap_dsp

echo "AEWB $cap_dsp $cap_ex2 $cap_vout $cap_af $cap_motor" > /var/tmp/sonia_para

if [ "$product_name" = "IPC-KW10W-0280B-ZH" ];then
    	sleep 3
	insmod /usr/lib/modules/g_ether.ko
	netinit if=eth0 default
fi

if [ "$product_name" = "IPC-HDW7243X" ] || [ "$product_name" = "IPC-HDW8241X-3D" ] || [ "$product_name" = "IPC-HDW7341X-B-E2" ];then
	echo host > /proc/ambarella/usbphy0
	insmod /usr/lib/modules/usbMst.ko
	busybox sleep 2;
	if [ "$product_name" = "IPC-HDW7341X-B-E2" ]; then
	/mnt/tmp/moviUsbBoot /mnt/tmp/movidius_ba_fireware.mvcmd
	else
	/mnt/tmp/moviUsbBoot /mnt/tmp/movidius_pc_fireware.mvcmd
	fi
	busybox sleep 2;
	insmod /usr/lib/modules/mvlog.ko id=4

	#使用moviUsbBoot烧写大固件时，文件系统缓存了许多Cache,故在这里释放Cache
	sync && echo 3 > /proc/sys/vm/drop_caches
fi

if [ $cap_wifi -ne 0 ];then
	ifconfig eth2 up
	
if [ "$product_name" = "IPC-C15" ] || [ "$product_name" = "IPC-C35" ] || [ "$product_name" = "IPC-C15-CE" ];then
	netinit if=eth2 default
else
	netinit if=eth2
fi
#	/usr/bin/wpa_supplicant -g/var/tmp/wpa_supplicant-global -P/var/tmp/eth2.pid &
fi

echo 1 > /proc/sys/net/ipv4/conf/all/arp_filter

if [ -f "/home/test.sh" ];then
	/home/test.sh &
fi
#蓝牙进程启动
if [ "$product_name" = "IPC-RM26-4G" ] || [ "$product_name" = "IPC-RM26" ] || [ "$product_name" = "IPC-RM26-4G-V2" ] || [ "$product_name" = "IPC-RM26-V2" ]; then
	bluetoothd 1 /dev/ttyS1 115200&
fi

#加载cifs驱动
insmod /lib/cifs.ko

if [ "$mp_autotest_flag" = "1" ];then	 	 
        systools selfTest &	 	 
fi